### ISSUE TITLE
CP* does not work as expected when it shall be used for gaining PTs

### ISSUE THREAD

**Issue by gereon77** [Longwelwind/swords-and-ravens#102]
- [ ] The option to get power tokens still appear after one muster point is already used

- [ ] Toggle between "Get 2 Tokens" and "Get 1 Token" depending if there is a star symbol on the area or not

- [ ] No power token is retrieved when choosing this option at all

- [ ] CP* can be played on normal areas and then you can muster to every castle you control but cant Confirm and game is stalled
![image](https://user-images.githubusercontent.com/22304202/72529150-f702ca00-386c-11ea-83a6-014232689395.png)

**Comment by gereon77** [comment]
In fact there are several issues here.

- [ ] Toggle between "Get 2 Tokens" and "Get 1 Token" depending if there is star symbol on the area or not
- [ ] No power token is retrieved when choosing this option

**Comment by gereon77** [comment]
Another important feature for „Resolve CP orders phase“ is missing. In case a player has CP* AND CP orders on the map he must be able to resolve the normal CP first and get the according power tokens. Then the next player in turn order may resolve one of his CP* and therefore the first player may reconsider his decision to muster or get power tokens depending on the amount of the power tokens of all others...

**Comment by Longwelwind** [comment]
You're right that it could be used to delay a mustering.

I chose to implement it this way to save time on the resolving of the orders. Is it something that happens frequently?

**Comment by gereon77** [comment]
TBH.. Yes.. at least I use that regularly..

**Comment by Longwelwind** [comment]
Ok, I'll create an other issue for this, as the points raised in the first post are fixed by #131.
