### ISSUE TITLE
Add an indication that a single mustering can be removed by clicking the item in the list

### ISSUE THREAD

**Issue by gereon77** [Longwelwind/swords-and-ravens#104]
![DE790A0A-F2BE-45D0-842E-CF806AB9D84D](https://user-images.githubusercontent.com/22304202/72329501-253da980-36b5-11ea-9e6a-ea5b795eeeb5.jpeg)

Due to supply i can’t use the last muster point as desired. Instead of the footman I want to reconsider my decision and upgrade this footman to an Knight. So please either provide an undo button or an additional upgrade action for this footman. Current work around is to reload the page but then all previous musters are also gone. Nevertheless => low prio.

**Comment by Longwelwind** [comment]
IIRC, as a temporary workaround, you can click on the lines of text in the lists to remove them from the mustering.

**Comment by gereon77** [comment]
@Longwelwind Can we simply fix that by adding a X button after each line to remove a single mustering? The functionality is already there but it's not obvious...
