### ISSUE TITLE
Potential bug with Doran Martell and Valyrian Steel Blade

### ISSUE THREAD

**Issue by mrhappyasthma** [Longwelwind/swords-and-ravens#1161]
We just hit an interested edge case and I'm not sure if it's working-as-intended or a bug. The rules do not seem to be cut-and-dry here. (https://images-cdn.fantasyflightgames.com/filer_public/30/4f/304f72e3-4fe4-4f91-bfbe-75133161b092/va65_agot2_rulebook_web.pdf)

It does not seem touched upon in the FAQ/errata either (https://images-cdn.fantasyflightgames.com/filer_public/cf/06/cf06eb26-48e3-46b9-b57c-f053beb2518d/agotbg_faq_v2_forweb.pdf).

Order of operations:

- Before combat, Tyrell was at the top of Fiefdom track and the sword was still available for this round. Martell was 2nd on the track.
- During combat, Martell uses `Doran Martell`.
- Martell immediately moves Tyrell to the bottom of Fiefdom track

Once combat is resolving, I would expect the behavior to be that Martell (the current holder of the blade) can now use it in combat. However they were not presented with that option.

(happen in the middle of Turn 8 in this game: https://swordsandravens.net/play/df2091c2-c51d-404d-91d8-82b57c3e853c)

**Comment by gereon77** [comment]
Hi @mrhappyasthma !

Thx for your report. Where exactly do you think a bug occurred? Everything looks good to me. Even if Tyrell chose to Burn the VSB, it was useless as during the UseVSB timing window, they were not longer holder of the blade and thus the blade is still unused.

Martell were not able to use it directly in that battle because it was a 6 vs 8 and the use of the blade would not have changed the outcome.

**Comment by mrhappyasthma** [comment]
`Martell were not able to use it directly in that battle because it was a 6 vs 8 and the use of the blade would not have changed the outcome.`

Ah... so the game bypasses the blade if it cannot make a difference?

Perhaps this is where the confusion was. I was under the impression the Martell player was not given the option to use it all (when they should have). But i suppose it was because a +1 advantage would not make a tangible difference, so perhaps the game engine just skipped that ask (as a convenience).

If the battle had been within 1, would the Martell player have been given the option?

**Comment by gereon77** [comment]
Yes, as Martell is the new blade holder he can use it for this battle of course.

With the introduction of Vassals the blade resolution became a bit more complex as the blade holder is no longer always on top of fiefdom. And as the blade can also be used on behalf of a vassal we now have to compare the track positions of both combatants and have to check if it is enough to equalize or if the blade must be used to reach enemy combat strength +1.


In addition the question will always arise in case one of the MoD cards are involved where the final combat strength matters regarding the amount of power tokens to gain. Independent from the outcome of the battle the VSB holder might want to use it to increase or decrease the final difference…

**Comment by mrhappyasthma** [comment]
Good to know. This matches my expectations then.

Thanks for the context!

(Our Martell player wanted to use it ceremoniously as a form of 'taunt' against the other friend. Which is why we were unsure if it was a bug or not.)

**Comment by gereon77** [comment]
Yea this is done because it would drastically slow down PBEM games when the game would always ask for the VSB, even if it makes no difference. 

Except for the case you described with your Martell 😂, players will always choose not to use it..
