### ISSUE TITLE
Confusing UI when forced to play 'restricted orders'

### ISSUE THREAD

**Issue by mrhappyasthma** [Longwelwind/swords-and-ravens#1164]
Round 10 of this match as Stark (https://swordsandravens.net/play/df2091c2-c51d-404d-91d8-82b57c3e853c).

`Defense Orders` cannot be played this round. But I cannot ready until I attempt to put tokens on every spot.

I actually had to put the restricted (greyed out) tokens down before I could Ready (see attached image)
![wtf](https://user-images.githubusercontent.com/1547356/133013464-8137e894-24d2-4915-85ce-5c01ffb42a82.PNG)

Yet when I play this then trying to `Ready` gives me a warning about these restricted orders: 
![wtf2](https://user-images.githubusercontent.com/1547356/133013499-caa4cdcf-27e3-4c7f-b15b-041c04b08cff.PNG)

Should the UI let me ready before forcing me to play restricted orders? Because otherwise it forces you into this error dialog. (Accepting the dialog should be fine, since they will just be removed anyway since they are invalid. But making the user go through this feels strange.)

Is this working-as-intended or something that can be improved?

**Comment by gereon77** [comment]
Hi @mrhappyasthma !

this is intended behavior as the game forces you to place an order in every region with units. So instead of revealing which region you don’t fill with an order, we allowed placing restricted orders as dummy orders.

Cheers

**Comment by mrhappyasthma** [comment]
Ah, I see. That's a nice touch.

It was a bit confusing at the time, but I think it's handy to keep your opponents on their toes.
