### ISSUE TITLE
Feature request: Forced/skipping turns

### ISSUE THREAD

**Issue by alecejones-noodoe** [Longwelwind/swords-and-ravens#1182]
I wanted to bring up an optional feature request to deal with the problem of lagging players in games, and causing games to drag on endlessly.

I don't know if someone has already proposed this.

This feature is the forced turn option. It will be available only to the game host to invoke.

Conditions:
Whenever the current turn changes to a new player, a time interval begins that may be short (1 hour) or long (24-36 hours). Something tied to a timestamp of the last completed turn.
After this time, a forced turn feature activates.
The forced turn could occur automatically, or it could be done by choice of the host, who is prompted with an email that current player has passed their time limit.

Forcing a turn will have different effects:

1) If that player is in battle, draw a card at random.
2) If using VSB, choose not to.
2) If in bidding, bid zero.
3) If placing orders, select at random, with preference for starred orders.
4) If making a move, remove order token without doing anything.
5) If consolidating power, take tokens.

All skipped turns will be recorded in the log.

It's overly harsh but I think appropriately punitive for serial time wasting players. It also is less drastic than calling a vote to replace a player completely, but probably goes well with replacing players after X turns of being skipped.

The timeout feature and log prevents the feature from being abused by the game host.

It should remain an optional feature because i know some people won't want to play with it in things like tournaments.

**Comment by gereon77** [comment]
Hi! A similar idea was brought up by Tex already but it’s a lot of work to extend every possible game state with auto actions. You just listed a few main states but combat phase alone can trigger many different child states (house cards, casualties, retreat).

Due to complexity and risks of this feature I put it as not planned for now.

**Comment by gereon77** [comment]
Finally solved by #1486
