### ISSUE TITLE
Strange game states

### ISSUE THREAD

**Issue by gereon77** [Longwelwind/swords-and-ravens#123]
Unfortunately I can't reproduce them but I saw following strange scenarios:

- Westeros event "Game of Thrones" triggered by "Dark wings, dark words" didn't work
- Wilding victory Preemptive Raid lead to a stalled game (1player...)
![image](https://user-images.githubusercontent.com/22304202/72691257-58a08e00-3b24-11ea-85c4-df5890acaa15.png)
Cant continue here...

**Comment by Longwelwind** [comment]
The first bug has been resolved by a previous issue.

The second issue happens because there's only one player. I close since having one-player game is not planned in the game.
