### ISSUE TITLE
Implement a victory track

### ISSUE THREAD

**Issue by gereon77** [Longwelwind/swords-and-ravens#124]

**Comment by Longwelwind** [comment]
I'm not sure about this one. The info is already available in the Houses panel (at least, the number of strongholds each house posses) and I feel like adding yet another bar will clutter the UI.

I put it as low priority for now.

**Comment by gereon77** [comment]
Ok.. well.. maybe it’s possible to order the houses by the leading ones?

**Comment by gereon77** [comment]
I close this as house panels are sorted by leading players now and that should be enough as a victory track.
