### ISSUE TITLE
Sign-in w/ Google OAuth2.0 is failing

### ISSUE THREAD

**Issue by mrhappyasthma** [Longwelwind/swords-and-ravens#1241]
See image. I'm getting this error when trying to log in w/ googl
<img width="574" alt="Screen Shot 2021-11-03 at 5 28 25 PM" src="https://user-images.githubusercontent.com/1547356/140237415-de10a038-4bec-4718-b39e-ec36637926d9.png">
e.

**Comment by Longwelwind** [comment]
Fixed with #1243 🙂

**Comment by gereon77** [comment]
@mrhappyasthma can you confirm it’s fixed for you?

**Comment by mrhappyasthma** [comment]
I confirmed that this is now working again. Thanks!
