### ISSUE TITLE
Players should be allowed to resolved normal CP tokens before starred CP tokens.

### ISSUE THREAD

**Issue by Longwelwind** [Longwelwind/swords-and-ravens#134]
Created following #102

**Comment by gereon77** [comment]
Clicking Submit on a CP* on a non castle area adds strange log messages:

![image](https://user-images.githubusercontent.com/22304202/72691303-aa491880-3b24-11ea-87d7-65071987593b.png)

**Comment by gereon77** [comment]
@Longwelwind i plan to continue with this. Any suggestions or can I go straight forward?

**Comment by Longwelwind** [comment]
I would remove the automatic resolution of the normal CP token and modify `PlayerMusteringGameState` to allow the resolution of a simple consolidate power.

If you feel like you can do it, feel free!

**Comment by gereon77** [comment]
I think it's an important feature as depending on decisions of other players you might want to resolve a CP* for Power Tokens to stay the richest guy or in case others used it for mustering you also want to muster to stay the strongest guy...

I planned to keep the automatic resolution when there is no CP* and only in case there is a CP* it will be delayed. In case the CP* is used all remaining CPs should be resolved automatically. I haven't looked at the code in detail yet to estimate how much effort it will be but I guess I can deal with it.
