### ISSUE TITLE
Supply is not respected through all phases of march

### ISSUE THREAD

**Issue by gereon77** [Longwelwind/swords-and-ravens#140]
I was on standard Martell supply of 3,2,2 and did following move from Highgarden:

1 FM -> storms end (storms end was not highlighted probably because i exceed supply limit here but i could select it)
1 FM -> reach
1 FM -> storms end

The game allowed me to do this move probably because supply limit was OK again after all units were moved but in fact the first part of the move would have exceeded my supply limit because of 4 armies.. 

![image](https://user-images.githubusercontent.com/22304202/73055992-44df8980-3e8e-11ea-90d5-f37cc99e5ccc.png)

![image](https://user-images.githubusercontent.com/22304202/73056022-51fc7880-3e8e-11ea-9baf-f0febece935e.png)

**Comment by Longwelwind** [comment]
From my point of view, everything is normal:

* The game should allow you to do this move since a move is legal if supply is respected after *all* movements are done.
* It's normal that Storm's End was not highlighted because this move _alone_ would have broken your supply limits. The game should not have allowed you to send this footman.

**Comment by gereon77** [comment]
> From my point of view, everything is normal:
> 
> * The game should allow you to do this move since a move is legal if supply is respected after _all_ movements are done.


That’s not true. Rule book says supply must be respected all the time and must not be exceeded during a march even if the final position would be OK again. That’s important! There are cases which prevent you to move as you want by this rule.

**Comment by gereon77** [comment]
“ ɇ A player is never allowed to take any action in the game that would cause him to exceed his actual supply limit as dictated by his position on the Supply track (such as mustering, marching or retreating, all explained later).”

**Comment by Longwelwind** [comment]
In my opinion, you process _all_ moves of the March order at once, regardless of the order in which you put them through the UI.

In your case, it would even be valid if you first did the move to **The Reach** and then do the move to **Storm's End**.

The situation that obviously must be prevented is a player breaking the supply limits with a March Order thinking that he could then "resolve" it with a second March order.

**Comment by gereon77** [comment]
Yea at this example you’re right. I could have done it in a way that wouldn’t exceed my supply limit. But with other players that must no necessarily be the case. Consider Reach to be occupied by another player and you have only your areas to move around. Then it may make a difference. In fact it happened just two times to me (more than 500 games) that I couldn’t do what I want to do because I haven’t seen that...

But let’s assume you play the game on the real board. When you resolve a march you take a unit and move it immediately to the area you want to. If you then break in between and look at the board you have a state where you exceed supply limit and that is just not allowed. Tbh it’s a rare case and therefore it’s hard to provide a good visual example which would make it clear why it has to be implemented this way...

**Comment by Longwelwind** [comment]
I disagree, though. I can't prove it but I think you can always find an order of moves that would satisfy the supply limits.

There is something I have not considered, though.

![image](https://user-images.githubusercontent.com/9724878/73257653-72953d00-41c4-11ea-9819-9e0b49547355.png)

I believe it is not taken into account at the moment in the game.

**Comment by gereon77** [comment]
> I disagree, though. I can't prove it but I think you can always find an order of moves that would satisfy the supply limits.

Trust me there are very rare situations.. I will try to find an example. Two times I planned to do sth but I weren't able to do so because an in between state would have broken supply and I haven't seen that coming...

And the screenshot you appended confirms this issue even more... From my point of view the marches should be sent as ordered arrays and every march in it should be checked against supply...

**Comment by gereon77** [comment]
But yes.. probably that is only an issue when it comes to a battle. When we stay at the Screenshot in the first comment. Consider all landareas around HG occupied by an enemy and one foot man shall attack eg storms end.. then we have the non allowed situation..

Nevertheless I would always check every move and I continue on trying finding an example why..

**Comment by gereon77** [comment]
So I played around using money coins as armies and units. In fact I weren't able to construct a non battle situation where any in between position violates supply but the final one was good again. So probably the two times I mentioned I wanted to start a battle but were not able to.

Nevertheless I would implement it this way because you plan to visualize the movement of the unit into the target area immediately when the user clicked the target area. If the movement violates supply a messagebox "supply violation" should be shown and after confirming the movement is rejected. That forces the user to perform his march in a valid order and will also fix the issue when it comes to battle.

**Comment by gereon77** [comment]
I guess your retreat supply check strategy satisfies this now. I also tested this scenario without a march and now the server only accepts marches in the correct order.

**Comment by gereon77** [comment]
That seems still to be an issue:

![35821274-7CCB-47E1-B080-65E57827174A](https://user-images.githubusercontent.com/22304202/81592835-d41d9800-93be-11ea-9ab5-a13fff63132f.jpeg)

![8ADBDE9A-57CC-4BCF-8738-271160131BB7](https://user-images.githubusercontent.com/22304202/81592867-e39ce100-93be-11ea-9474-a4baf1063ef7.jpeg)

**Comment by Longwelwind** [comment]
I think the issue is that `getValidTargetRegions` doesn't discriminate between combat moves and non-combat moves when it comes to supply issue:

```
.filter(r => !this.doesMoveExceedSupply(startingRegion, new BetterMap(moves.concat([[r, movingArmy]]))))
```

I think it should not be `moves`, but `movesThatDontTriggerAttacks`.
