### ISSUE TITLE
Siege Engine limit not respected through mustering

### ISSUE THREAD

**Issue by gereon77** [Longwelwind/swords-and-ravens#141]
![image](https://user-images.githubusercontent.com/22304202/73056078-735d6480-3e8e-11ea-9ac9-e3b632dd1c5c.png)

![image](https://user-images.githubusercontent.com/22304202/73056122-88d28e80-3e8e-11ea-9974-31213b788a53.png)

**Comment by Longwelwind** [comment]
What was your supply limit during this mustering?

**Comment by Longwelwind** [comment]
Nevermind, I understood the issue!
