### ISSUE TITLE
locally run game server not working with empty host

### ISSUE THREAD

**Issue by PeiyuanQi** [Longwelwind/swords-and-ravens#1479]
I tried to run `yarn run run-server` for agot-bg-game-server with node v16.14.0 (npm v8.3.1) yarn version v1.22.18 but it throws an error of empty host address.
I see in src/server/server.ts line 13, optional value host is not specified, wonder it is left intensionally or not? If so, is there any missing config i need to do to run the server?

**Comment by gereon77** [comment]
Hi. See https://github.com/Longwelwind/swords-and-ravens#launching-the-game-only


To run the project, nodeJS v14 is required.

**Comment by PeiyuanQi** [comment]
ah i see, sorry miss the required, thought it was 14 and up.
