### ISSUE TITLE
Allow priviledged players to play a game as an other players

### ISSUE THREAD

**Issue by Longwelwind** [Longwelwind/swords-and-ravens#15]

**Comment by Longwelwind** [comment]
The feature is coded, but it is not restricted at the moment, meaning that any player can play as any player.

A Django permission should be created to allow only privileged users to do this.

**Comment by gereon77** [comment]
@Longwelwind maybe that could be the next thing to do for the MVP?

**Comment by Longwelwind** [comment]
Indeed! I fixed that. :)
