### ISSUE TITLE
Declare support phase needs to be clarified

### ISSUE THREAD

**Issue by gereon77** [Longwelwind/swords-and-ravens#153]
![B811E64D-B047-467B-B60B-B38BDDA18949](https://user-images.githubusercontent.com/22304202/73158425-0f33de00-40e4-11ea-996c-88adcd746d2f.jpeg)

From that reading it sounds like a supporting player can decide that he supports the attacker or defender from area A but not necessarily from area B too...

**Comment by Longwelwind** [comment]
As discussed on Discord, the two erratas contradicts themselves, but I think we can assume that a player either commits all of their troops or none of their troops.

We could allow a player to support only with some parts of their troops, but I feel like it would complicate too much the process. At the moment, I'd rather only support this.

If that's okay with you, we can then close the issue.
