### ISSUE TITLE
Bug: request support against a neutral force is available in a game with locked areas of the map

### ISSUE THREAD

**Issue by hadook** [Longwelwind/swords-and-ravens#1575]
Playing a Feast for Crows in this particular game as Baratheon.
https://swordsandravens.net/play/e24780ab-38fb-456e-8c10-5bfc4020cd36

Baratheon has a March order on Storm's End. Lannister has a support order on the Reach. As a Baratheon, I was given the option to call for support against a neutral force. Upon clicking the button, the game log showed Baratheon requested support against the neutral force at The Boneway. The Boneway is a locked area in this game mode and there is no neutral force there.

Note the top of the game log box (left side) in the screenshot.

![ffc_neutral force_support](https://user-images.githubusercontent.com/18307813/182797311-3e5a9755-e697-42cc-b4b9-0f2adc61eb11.png)

**Comment by hadook** [comment]
Lannister's perspective:

![292065548_1198054867433977_8388954204966920289_n](https://user-images.githubusercontent.com/18307813/182799666-be3fda0c-a484-4ab4-9b35-05eb827490d8.jpg)

**Comment by gereon77** [comment]
😬 Thx for this report! It will create no issues at all, as we block off limits areas with garrisons of value 1000 and no support will ever allow to take that regions but of course we should filter for that. I’ll fix it asap!
