### ISSUE TITLE
Wildling card "Preemptive Raid" should not affect the Wildling track strength.

### ISSUE THREAD

**Issue by hadook** [Longwelwind/swords-and-ravens#1578]
Please note that this is my interpretation of the rules as written. I haven't found an answer in the FAQ, but I assume the correct behaviour for the "Preemptive Raid" wildling card should be different than the current implementation.

The "Preemptive Raid" card reads as follows for the "Night's Watch victory" section:
`The wildlings immediately attack again with a strength of 6. You do not participate in the bidding against this attack (nor do you receive any rewards or penalties).`

**Scenario**:
The wildling card "Preemptive Raid" is drawn and the Night Watch wins, immediately resulting in another wildling attack with the strength of 6.

**Current behaviour**:
The wildling strength track is set to 6, regardless of its previous position. A wildling card is drawn and bidding ensues.
- In case of the Night's Watch victory, the wildling track is set to strength = 0 after the card effects are considered.
- In case of Wildling victory, the wildling track is set to strength = 2 (moved 2 positions to the left from strength =6) after the card effects are considered.

**Expected behaviour** (in my opinion):
The wildling strength track remains unaffected, the card and the victory or defeat does not affect the wildling strength token position on the track.

**Example in-game**:
Consider this example in Round 5.
https://swordsandravens.net/play/e24780ab-38fb-456e-8c10-5bfc4020cd36

1. Wildling strength = 0.
2. A wildling attack triggered, Night's Watch was victorious.
3. The card drawn was "Preemtpive Strike". Wildlings attack again with a strength of 6.
4. The Wildlings were victorious. After this attack, the wildling strength was set to 2, where it should have remained at 0.

**Comment by gereon77** [comment]
Well the question is, if

![A4E26CD9-7590-4C08-91CD-812341FCABAB](https://user-images.githubusercontent.com/22304202/183115243-56a2b254-deca-41d7-a95a-28fecc324e8f.jpeg)

Means to adjust the position in case of they attack again with 6. From my point of view, yes, but to be sure, I’ll ask Tex to ask Jason, the designer.

**Comment by hadook** [comment]
I'd argue that since the card text reads "the wildlings immediately attack again with a strength of 6", it instructs the players to consider a wildling attack, where the first step (determining strength) is determined by the card itself rather than reading the strength from the track.

But I can see why it could be interpreted otherwise, that's why I noted that it's just my understanding of the rules. Thanks for investigating! :)
