### ISSUE TITLE
Resolving order of tracks is unhandy

### ISSUE THREAD

**Issue by gereon77** [Longwelwind/swords-and-ravens#159]
![image](https://user-images.githubusercontent.com/22304202/73258169-71b0db00-41c5-11ea-9c68-72fba87df8e5.png)

Cant make it work to place the order I want. Bara, Lanni, Tyrell, GJ

I guess on 6p games this might be even worse. How is this intended to work? Shall I click a house symbol and move it then?

I managed it finally but I don't know how I finally came to that result...

**Comment by Longwelwind** [comment]
You click the arrow below a house to move it on the lift or on the right.

For example, in your case, you'd only need to click on the right arrow below Lanni, or the left arrow below Tyrell.

We could use a drag'n'drop system, which would be more intuitive. It would be more complicated to implement than this system, though.

**Comment by gereon77** [comment]
Aaaaaahh thx for clarification.... -_-

**Comment by gereon77** [comment]
@Longwelwind 
I also plan to improve this by adding the biddings to the action pane and game log. That will help the chooser and all others to see the possible order. Do you agree?

**Comment by Longwelwind** [comment]
IIRC, it's already printed in the game logs, but after the resolution is done. The best would be to print it after the bidding is done, and then print the final order after the order resolution is done.

Regarding the UI, do you think simply adding the bid between the house icon and the arrows would be enough to clarify the UI of track order resolution? If yes, then we can imply do that.
