### ISSUE TITLE
Allow private chat rooms to be created

### ISSUE THREAD

**Issue by Longwelwind** [Longwelwind/swords-and-ravens#160]
Following from #5

One question: should we allow private rooms with multiple players to be created?

**Comment by gereon77** [comment]
> One question: should we allow private rooms with multiple players to be created?

Yes why not. That makes arrangements between more than 2 players easier.

**Comment by Longwelwind** [comment]
OTOH, allowing channels with multiple players makes it harder for players to lie to each other. Like if a player tells 2 different things to 2 different players. It's easier to achieve that when the game forces only 2-players chat rooms.

**Comment by gereon77** [comment]
Well of course you should be able to create a room with player A and a second room with player A and B which would make it possible again to lie...
