### ISSUE TITLE
Players don’t receive their house cards after replacing a vassal

### ISSUE THREAD

**Issue by gereon77** [Longwelwind/swords-and-ravens#1602]
https://swordsandravens.net/play/c66d1a29-3af8-4692-add8-303964c39731

**Comment by hadook** [comment]
I replaced a vassal in this game (outside of combat) and immediately got regular house cards, as expected.
https://swordsandravens.net/play/84faee7c-339a-46e9-b217-7ee8e781b88b

**Comment by gereon77** [comment]
But here the same happened to House Arryn:

 https://swordsandravens.net/play/0ee27e39-589f-4ee4-b3d0-574f06659751

**Comment by gereon77** [comment]
And here to Baratheon:

https://swordsandravens.net/play/e3c837b0-a5f7-43b1-9d50-75b71d47d985

**Comment by gereon77** [comment]
> I replaced a vassal in this game (outside of combat) and immediately got regular house cards, as expected.
> https://swordsandravens.net/play/84faee7c-339a-46e9-b217-7ee8e781b88b

Thanks! This helps and leads me to the assumption that it only works for vassals which have been replaced before I deployed 

https://github.com/Longwelwind/swords-and-ravens/commit/ff097882d5fedd752f9926ea030d8f669ed2095a


And

https://github.com/Longwelwind/swords-and-ravens/commit/0a187595d232195e4081f08a145ba4be127fb4ba


I think one of those commits bugged the replace vassals feature
