### ISSUE TITLE
Aeron Damphair is not discarded after use

### ISSUE THREAD

**Issue by gereon77** [Longwelwind/swords-and-ravens#164]
![image](https://user-images.githubusercontent.com/22304202/73317424-46b29f80-4236-11ea-878a-3cc66b610c22.png)

And the chosen card after Aeron is not displayed in Games Log... (Asha in that case)

**Comment by gereon77** [comment]
seems only to be an UI issue as Aaron cant be selected and after Reload he is discarded

**Comment by Longwelwind** [comment]
IIRC, I didn't code a lot of logs for House cards (I went quickly through to them to get a first implementation of them all).

I'll fix the issue of the card not being shown discarded directly, and I'll add a comment in #17 mentionning the lack of logs for House cards.
