### ISSUE TITLE
Game lobby improvements

### ISSUE THREAD

**Issue by gereon77** [Longwelwind/swords-and-ravens#167]
- [x] Add button to leave joined games
- [x] "Join" button should be renamed to "Rejoin" if user already joined
- [x] Highlight the games where it’s your turn

**Comment by gereon77** [comment]
Leave button is a bit buggy. It should be shown just for me. Clicking someone else’s Leave button results in me leaving the game...

**Comment by Longwelwind** [comment]
Should be good now!

**Comment by gereon77** [comment]
@Longwelwind A few days we have spoken about what is necessary for a MVP. I guess the "Highlight games where it's your turn" thing is something which definitely should be done. It will help the users as they then just need to visit the Games route and see if they have to proceed in one of their games. Right now they need to click through all games to see whats going on. Unfortunately I can't help here implementing that.
