### ISSUE TITLE
March order hides a unit of a three unit army in Pyke so it can't be selected for movement

### ISSUE THREAD

**Issue by gereon77** [Longwelwind/swords-and-ravens#168]
![image](https://user-images.githubusercontent.com/22304202/73355084-907fa200-4297-11ea-973f-ea74213bdf86.png)

![image](https://user-images.githubusercontent.com/22304202/73355168-c6248b00-4297-11ea-92fb-ae25ffe11157.png)

**Comment by gereon77** [comment]
@Longwelwind 
I have a possible fix at https://github.com/gereon77/swords-and-ravens/tree/rearrange-slots-for-greyjoy


Original:
![image](https://user-images.githubusercontent.com/22304202/73847060-d6071680-4825-11ea-9204-3a871e0ac7e3.png)


My Branch:
![image](https://user-images.githubusercontent.com/22304202/73846782-62650980-4825-11ea-8ddf-5cf783e2bb8c.png)
![image](https://user-images.githubusercontent.com/22304202/73848861-38ade180-4829-11ea-9fc3-c994ff9a92f7.png)


I also moved the Ironmans Bay Order nearer to the ships as in case you don't assign the port but Ironman's bay you might think the order is for the port.


The unit overlay will never happen as you can't have two 4 unit armies though 4 unit armies will probably be problematic in other regions....

**Comment by Longwelwind** [comment]
Looks good to me, you can create a PR!
