### ISSUE TITLE
Rework the way map controls are used by GameState

### ISSUE THREAD

**Issue by Longwelwind** [Longwelwind/swords-and-ravens#174]
At the moment, `MapControls` offers an interface for `<GameState>Component` to interact with the map shown in the middle of the screen. This allows GameState to highlight units, regions, add logic when an unit is clicked, ...

The structure of this API is cumbersome and makes it hard to extend. Multiple things would need to change:

* Instead of having a function by GameState that is evaluated for each unit, have a function that is called once, and gives the list of units/regions that must be modified
* Make this function returns a full object with all modifications (highlighting, onClick logic, ...) instead of having one function for each modification.

This would make it easy to add other special effects such as units/regions highlighted in other colors or else.

**Comment by Dode123** [comment]
Being able to show regions in different colors (depending on who controls them) would indeed be great :)
