### ISSUE TITLE
Make reconciling only allow the least number of units to be killed

### ISSUE THREAD

**Issue by Longwelwind** [Longwelwind/swords-and-ravens#178]
At the moment, during reconciling, a player can kill any number of units as long as the supply limits are respected. This means he can kill units that doesn't help respecting supply limits, which is forbidden by the rules.

**Comment by Longwelwind** [comment]
I propose to remove this off the Base Game milestone and leave this for after we have a working base game. I guess it's rarely in the interest of a player to remove more units that he needs to for a supply reconciliation.

We'll discuss later on how to implement this.

**Comment by gereon77** [comment]
@Longwelwind Actually I already suggested a solution:

https://github.com/gereon77/swords-and-ravens/tree/reconcile-with-lowest-casualties

**Comment by Longwelwind** [comment]
I think there's an easier way to solve this:

* Take the list of removed units chosen by the player
* Check if removing one removed unit of the list would still make a correct reconcilement.

On top of that, the method we would implement should allow us to know whether one unit can be chosen for supply reconcilement, to allow us to highlight correct units to be chosen in the UI.

**Comment by gereon77** [comment]
Indeed. My approach was quick and dirty to disallow killing all or single units.. As I am at home with a bands tore I maybe will find time to implement this idea.

**Comment by gereon77** [comment]
@Longwelwind  Just one question.. when i just check the selected units if a subset of them would be sufficient also, how do i catch less expensive costs by not selected units. Consider switch from 3-2-2 to 3-2:


User has following armies:

FM-FM-FM
FM-FM
KN-KN

When user decides to kill a knight at least there should be a warning that it could be done with lower casualties...

**Comment by Longwelwind** [comment]
>Indeed. My approach was quick and dirty to disallow killing all or single units.. As I am at home with a bands tore I maybe will find time to implement this idea.

I understand! Do you think you could focus on other issues in the milestone for the moment. I know it's less fun than implementing new features or mechanics, but they are things that will need to be done like testing and UI fixings.

>When user decides to kill a knight at least there should be a warning that it could be done with lower casualties...

I don't get how in your example a reconciliation could be done with lower casualties. Killing a knight is a correct reconciliation.

There shouldn't be any warning for this I think. We can have an other discussion on warnings as I'm not sure it's necessary to put warnings for _everything_. It's usefull for really rare situations, but for normal operations like resolving a March order without doing any movements, resolving a raid order with no target or doing a not optimal reconcilation. Too much wanings will impact UX and frustrate advanced players who know what they are doing, imo.

I'm usually a perfectionist for these things, but I don't mind leaving reconciliation as it is for the moment if it can help us focus on things that matter and help us make a finished game faster. Specially since the rules are not clear about this anyway.

**Comment by gereon77** [comment]
> I understand! Do you think you could focus on other issues in the milestone for the moment. I know it's less fun than implementing new features or mechanics, but they are things that will need to be done like testing and UI fixings.

Sure. I will do so.

> > When user decides to kill a knight at least there should be a warning that it could be done with lower casualties...
> 
> I don't get how in your example a reconciliation could be done with lower casualties. Killing a knight is a correct reconciliation.

Yep but choosing a FM from FM-FM would be less expensive..

**Comment by Longwelwind** [comment]
>Yep but choosing a FM from FM-FM would be less expensive..

This is too much opinionated. Even in AAA games, you don't get this kind of warnings. In Hearthstone, if you finish your turn while still having mana gems, you don't get a warning, for example.

**Comment by gereon77** [comment]
Alright.. I see that point. You don’t have warnings at home games as well but maybe the host may warn you before a guest does a suspicious move. So I thought an online adaptation could be this friendly as well but no problem. I move this issue back to the backlog.
So what’s next where I could help?

**Comment by gereon77** [comment]
Closed by #775 as preparation for vassals
