### ISSUE TITLE
How and where stored regions and borders

### ISSUE THREAD

**Issue by TatProg** [Longwelwind/swords-and-ravens#1794]
Hi!
I want to develop a mathematical model that calculates value of each Westeros's region _(depending on the starting map and input weights)_. So I found regions in `agot-bg-game-server/data/westeros.json`, but couldn't find file that describe connections between them. 
How army moving or connections and borders work in this game?

**Comment by gereon77** [comment]
Hi @TatProg !

The file you’ve found has been created with a Tool called 'Tiled'. It’s exactly what you’re looking for and contains all elements on the map, including all the borders. They are used to calculate the world with its regions and their connections and on client side they are used to calculate svg polygons for highlighting the areas. The core part is done here:

https://github.com/Longwelwind/swords-and-ravens/blob/master/agot-bg-game-server/src/common/ingame-game-state/game-data-structure/static-data-structure/globalStaticWorld.ts

https://github.com/Longwelwind/swords-and-ravens/blob/master/agot-bg-game-server/src/common/ingame-game-state/game-data-structure/World.ts

https://github.com/Longwelwind/swords-and-ravens/blob/master/agot-bg-game-server/src/client/MapComponent.tsx
