### ISSUE TITLE
Game does not work on Android

### ISSUE THREAD

**Issue by Dode123** [Longwelwind/swords-and-ravens#18]
The buttons (muster units, select areas to move, house cards etc) are not visible on android, even when using desktop-mode feature in Chrome Android. So can't resolve anything.

**Comment by gereon77** [comment]
@Dode123 Is that still true? Game works perfect on iOS... Apart from that it's not really responsive yet but it works...

**Comment by Dode123** [comment]
> @Dode123 Is that still true? Game works perfect on iOS... Apart from that it's not really responsive yet but it works...

No, it works now. So something must have been fixed since I logged this.. :)

**Comment by gereon77** [comment]
Thx :)
