### ISSUE TITLE
Turn order bug after Doran Martell

### ISSUE THREAD

**Issue by allarddolron** [Longwelwind/swords-and-ravens#1823]
![Schermafbeelding 2023-05-12 112045](https://github.com/Longwelwind/swords-and-ravens/assets/159783831/b688078f-6dcd-4f14-a91f-2b19ae3e8b61)

Tyrell was first in turn order (iron throne). He marched and Stark attacked with Doran Martell and chose that Tyrell was placed to the bottom of the iron throne. Now, it should be Greyjoys turn because he is the next in line (first now), but the game assigns the turn to the Baratheon (second now).  So Greyjoy is passed over.

**Comment by gereon77** [comment]
I really should release the PR which is adding an event log for this special situation. 😑 Anyways.. Please search issues before opening new ones. This is the third: #616 #676 


![IMG_4011](https://github.com/Longwelwind/swords-and-ravens/assets/22304202/f9cb20fd-0365-43eb-b90c-0ed40b6430cf)
