### ISSUE TITLE
Add background music for different game phases

### ISSUE THREAD

**Issue by gereon77** [Longwelwind/swords-and-ravens#186]
A friend of mine created 5 different samples which could be used for background music. I‘ll send you all s as one mp3 via mail or discord.

**Comment by Longwelwind** [comment]
Could be nice, and the music samples sounds cool, but definitely not a priority for the moment. I'd rather focus on core features to have a working MVP asap.

**Comment by gereon77** [comment]
Of course.. that’s why i worked on the port issues.. i just introduced this project to my friend and he came up with the orders and i thought.. well.. why not? But definitely nothing for now...

**Comment by gereon77** [comment]
Just a hint for me. If we implement that one day it should be done in the following:

Check the next sample to play depending on the current phase and just switch samples after one is completely over to allow fluent transitions.

**Comment by gereon77** [comment]
[SnR-background-sounds.zip](https://github.com/Longwelwind/swords-and-ravens/files/9099499/SnR-background-sounds.zip)
