### ISSUE TITLE
Implement restrictions for port regions

### ISSUE THREAD

**Issue by Longwelwind** [Longwelwind/swords-and-ravens#2]
Port regions have multiple restrictions, some are implemented, some are not. Here is the list:

- [x] A port can't support the adjacent land area.
- [x] Enemy ships can't march into the port if the adjacent land area is enemy-controlled (even if this port is empty).
- [ ] If a enemy takes control of the adjacent land area and if there are ships inside the port, the enemy can convert any ships present in the port to his house.
- [ ] If a house was controlling an enemy capital adjacent to a port, and mustered ships inside the port, but then decide to entirely move his land units out of the capital without leaving a power token, the enemy would then immediately take back control of the capital. The enemy must then choose to convert the ships to his house or destroy them.

**Comment by Dode123** [comment]
Also vassals can't march into port, but can retreat there.

**Comment by gereon77** [comment]
Regarding „If a enemy takes control of the adjacent land area and if there are ships inside the port, the enemy can convert any ships present in the port to his house.“

In fact the overtaking player can decide if he wants to convert ALL ships or none. Of course he has to follow his supply limit and can’t have more ships than available...

**Comment by gereon77** [comment]
Missing:

![image](https://user-images.githubusercontent.com/22304202/73541575-1b48d400-4433-11ea-8b59-1b9ec0abd3b1.png)
