### ISSUE TITLE
MapControls rework crashes Mammoth riders wildlings victory

### ISSUE THREAD

**Issue by gereon77** [Longwelwind/swords-and-ravens#232]
![image](https://user-images.githubusercontent.com/22304202/74691089-b4bd0780-51e1-11ea-96e7-f698a72b3a33.png)

I can't exactly say when that happens. It works sometimes and sometimes this error is thrown. Steps to reproduce:

1. Modify baseGameData.json to only hold wildlings attack cards in deck 3
2. Modify baseGameData.json to only hold mammoth-riders wildling card
3. Play as Baratheon and lose wildlings attack several times and remove different kind of units

My first assumption was that happens when the region is empty after the effect but I could not prove that. It worked the first time after removing all units from Shipbreaker Bay. The second time I removed all units from Dragonstone and the error was thrown.

**Comment by gereon77** [comment]
Tested on master...

**Comment by Longwelwind** [comment]
I think I found the cause of this. #233 should fix this!
