### ISSUE TITLE
UI elements improvements

### ISSUE THREAD

**Issue by gereon77** [Longwelwind/swords-and-ravens#254]
This issue is designated to discuss how UI elements like units, orders, tokens, etc. can be improved.

**Comment by gereon77** [comment]
- Order slot of Sea of Dorne could be centered
- Greyjoy ships should be southwest of pyke in 2 rows
- 3 unit army in Stoney Sept overlap with Lannisport border

**Comment by srr013** [comment]
It's difficult for a player to quickly distinguish orders requiring action (march, raid, consolidate power*) and then identify which units have been selected when a march order is selected. A simple fix requires only changes to CSS and would greatly increase visibility of these items. It does not appear that this change negatively impacts other parts of the game.

I suggest updating the CSS either to include increase the size of the drop-shadow effect for the medium-outline and strong-outline (and -hover) classes. You could optionally add color but this might have ramifications to usability for those with color blindness.

I put together the supporting documentation for this change here: https://docs.google.com/document/d/1zmDagDpjHzWBeHy1Aun2o8rYsiQXvz-bmeGedPJgg5M/edit?usp=sharing

**Comment by gereon77** [comment]
I really like this idea.. looks nice! Could you provide screenshots how it looks like for Lannister as he has red units?

**Comment by Longwelwind** [comment]
@srr013 I'm not fond of the colors, I like the white because it goes well with the rest of the UI. I agree with the increase of the intensity of the shadow, I also had some trouble finding which units I could select with the current shadow.

If you know how to, you can make a PR for this, otherwise I'll do it!

**Comment by srr013** [comment]
I went with the white highlighting per above feedback. PR sent.
