### ISSUE TITLE
Prevent users from multi accounting

### ISSUE THREAD

**Issue by gereon77** [Longwelwind/swords-and-ravens#256]
At least let’s block same IPs. On the one hand this would disallow gaming from the same network but does it happen that you meet with your friend to play GoT online? On the other hand you can’t prevent multi accounting completely. We all know there are ways to bypass this checks. So you just can minimize it...

**Comment by Dode123** [comment]
We should block same IPs, Thronemaster does this already. Quick fix, which at least makes it a little bit more work to multi-account.

**Comment by Longwelwind** [comment]
Note: IP addresses are PII (Personnaly Identifiable Information), so it should be noted somewhere that it is saved by S&R.
