### ISSUE TITLE
Add an indication to the embattled region

### ISSUE THREAD

**Issue by gereon77** [Longwelwind/swords-and-ravens#260]
Feedback from user is that you should be able to directly see where the battle happens. So it would be nice if there would be sword icons or something like this on the map during battle phase. Maybe the order slot can be temporarily used for this which is overlapped with a transparent image?

In addition the battle window should show the embattled region also. A title like "Battle for Winterfell" would be nice.

**Comment by Longwelwind** [comment]
Would highlighting the region in yellow do the job?

**Comment by gereon77** [comment]
Yea good idea! I also think the only state where regions will be highlighted is retreat and later maybe support (when enabling choosing support orders which participate) and that states will never include the embattled area itself. So I will add this to the PR if Ok for you.

**Comment by Longwelwind** [comment]
I already started on allowing `<GameState>Component` to allow highlighting regions of different colors, so if that's okay, I'll implement this change.

**Comment by gereon77** [comment]
Sure.. then I will just PR the title thing

**Comment by Longwelwind** [comment]
I think this is closed since both of our PR were merged.
