### ISSUE TITLE
Show game settings on the Games page

### ISSUE THREAD

**Issue by gereon77** [Longwelwind/swords-and-ravens#270]
So users see what kind of game they will join, for example:

- Player count
- Vassals
- PBEM/Live
- Automatic house assignment
- etc.

Maybe a settings dialog is shown when hovering over a specific game?

**Comment by Longwelwind** [comment]
Why can't it be set after the game has been created?

**Comment by gereon77** [comment]
Player count, vassal setup or hostless for example might be better to define before. So for example when I want to do a 3 player match without vassals I select 3 players, but no vassals and then the Game Lobby shows only 3 houses to select and the Games page shows something like 0/3 instead of 0/6. I think this way it feels more like a realization of a home board game where you also define the setup before you create it...

**Comment by Longwelwind** [comment]
I see.

My only gripe with this is that:

* We need to then replicate the form of the settings both in the game creation form and in the lobby.
* We could not show the settings form in the Lobby, I feel like people will want to modify settings after the game has been creatd. A case that I think might happen often is that players want to create a 8p game, can't find enough players who want to do that (let's say they are just 6), and thus wants to modify the number of players so they can start a game without having to recreate a new game.

**Comment by gereon77** [comment]
> * We could not show the settings form in the Lobby, I feel like people will want to modify settings after the game has been creatd. A case that I think might happen often is that players want to create a 8p game, can't find enough players who want to do that (let's say they are just 6), and thus wants to modify the number of players so they can start a game without having to recreate a new game.


Well.. can this be handled by allowing starting with at least 3 players and rest will be vassals then?

**Comment by gereon77** [comment]
> * We need to then replicate the form of the settings both in the game creation form and in the lobby. Which means also validating the settings in the website.


Would it be possible to just add a new React „CreateGameComponent“ where you can adjust the game settings and which will you then lead to the LobbyComponent?

**Comment by Longwelwind** [comment]
It could but I guess it would be the same problem than before.

I think it's not a bad idea to allow settings to be changed after the game has been created.

**Comment by gereon77** [comment]
> 
> 
> It could but I guess it would be the same problem than before.
> 
> I think it's not a bad idea to allow settings to be changed after the game has been created.

Indeed. When implementing the base game less player modes I realized that it is quite good that I can change the player count later and keep the game running. So I guess the real issue here is to properly pass the game settings to the Games page, so the users can see, what is currently set? I'll rename the issue.

**Comment by Longwelwind** [comment]
I think it's best to close this issue and recreate a new one with the new issue. Right now, someone discovering the issue and reading the conversation will get confused (In general, try not to edit conversations too much).
