### ISSUE TITLE
Influence tokens should be removed during Clash of Kings

### ISSUE THREAD

**Issue by gereon77** [Longwelwind/swords-and-ravens#286]
and be shown again after bid for a track is done. When bidding for Iron Throne it might be useful to keep the first influence token to see who will decide ties though.

**Comment by Longwelwind** [comment]
By "Influence Tokens", you mean the icons on the left of the pane in the UI? Because the concept of Influence tokens does not exist at all in the code, since an influence token always belongs to the first house on the influence track.

Hiding the influence icons during a Clash of Kings would make the UI more confusing, I feel.

**Comment by gereon77** [comment]
But that’s how it’s described in the rules and during a test game i found it confusing that we bid for fiefdom but still the old order has been shown..

![58253E34-02BA-4BCD-A519-AB74E656231C](https://user-images.githubusercontent.com/22304202/75756910-b6361600-5d31-11ea-9b4f-40460a2f2134.jpeg)

**Comment by Longwelwind** [comment]
Indeed, I thought you mean't dominance tokens. From a gameplay perspective, though, it still has absolutely no impact on the rules.

From a UX perspective, I understand the idea. We could the influence tracks during a Clash of Kings (maybe show dotted outline, like House cards in the Combat info). The implementation of this should not modify anything in the code that handles gameplay logic, it should only be graphical.

**Comment by gereon77** [comment]
> From a UX perspective, I understand the idea. We could the influence tracks during a Clash of Kings (maybe show dotted outline, like House cards in the Combat info). The implementation of this should not modify anything in the code that handles gameplay logic, it should only be graphical.

Yes, it's just UX and logic won't be affected.

**Comment by gereon77** [comment]
Do it client side note as we have to keep the iron throne track server side in case the current holder is replaced by a vassal during bidding for it...
