### ISSUE TITLE
Add own image for 'Winter is coming' of Deck 2

### ISSUE THREAD

**Issue by gereon77** [Longwelwind/swords-and-ravens#287]
As this might be confusing:

![image](https://user-images.githubusercontent.com/22304202/75690967-ffd81f80-5ca3-11ea-9840-a48a2bd03561.png)

It says new drawn card is A Throne of blade but Winter is Coming Deck 1 (which in fact is deck 2) is shown again.

**Comment by Longwelwind** [comment]
This will be harder to implement than it seems like because at the moment, we tie an image to the id of a `WesterosCardType` (in `westerosCardImages.ts`). One way to solve would be to modify `westerosCardImages.ts` to tie an image to the id of a `WesterosCardType` and a `currentCardI`.

**Comment by gereon77** [comment]
> 
> 
> This will be harder to implement than it seems like because at the moment, we tie an image to the id of a `WesterosCardType` (in `westerosCardImages.ts`). One way to solve would be to modify `westerosCardImages.ts` to tie an image to the id of a `WesterosCardType` and a `currentCardI`.

Wouldn't it also be possible to create `WinterIsComing2WesterosCardType` which calls the execute and executeImmediately methods from `WinterIsComingWesterosCardType` ?

**Comment by gereon77** [comment]
Well... `WinterIsComing2WesterosCardType` and `LastDaysOfSummer2WesterosCardType` would solve the issue and it doesn't look that bad from my point of view. No duplicated code blocks, just a few modifications (when we assume the 'Make WinterIsComing Generic' is done before, which I have done on a separate branch...):

![image](https://user-images.githubusercontent.com/22304202/75826267-6db93f80-5da7-11ea-9101-633b6ccf7b61.png)

![image](https://user-images.githubusercontent.com/22304202/75826330-92adb280-5da7-11ea-85a9-019ad1e25004.png)

https://github.com/gereon77/swords-and-ravens/tree/show-images-of-westeros-deck-2

**Comment by Longwelwind** [comment]
It's really not a good implementation to have `WinterIsComing2WesterosCardType`, from my point of view. At the moment, "Winter is Coming" are treated separately, but they shouldn't. They should be implemented with an `executeImmediately` function that would execute the effect of the card. In that case, creating a `WinterIsComing2WesterosCardType` would lead to code duplication.

The best way to implement it, for me, is to modify `westerosCardImages` so that an image is attributed for each `WesterosCardType` and westeros deck.

**Comment by gereon77** [comment]
Ok I understand. But as I inherited WinterIsComing2 from WinterIsComing there is no duplicated code.

Nevertheless.. give me a signal when i should PR the executeImmeadiately thing...

**Comment by Longwelwind** [comment]
A class inherited of the first class is an even worse than the previous one. Inheritance is not supposed to be used for those kind of use cases.

You can create the PR. It's a refactor so it won't be a priority to merge, but it will be there.

**Comment by gereon77** [comment]
Ok. No problem i try to fix it with binding to currentCardI. :)

**Comment by gereon77** [comment]
Closed by #367
