### ISSUE TITLE
Add notification for PBEM games when lobby is full and game is ready to be started

### ISSUE THREAD

**Issue by gereon77** [Longwelwind/swords-and-ravens#288]

**Comment by gereon77** [comment]
@Longwelwind I guess this becomes also more and more important.

**Comment by gereon77** [comment]
@Longwelwind what about up for grab?

**Comment by Longwelwind** [comment]
Do you have an idea on how to implement it?

I realize that I didn't write `CONTRIBUTING.md` clear enough, but in my mind, it's only if you want to work on a feature that you would ask it to be added into the `up for grab` list. 🙂

**Comment by gereon77** [comment]
I haven't dived into the notification code yet and therefore I have no idea. But yea.. You're right. I haven't thought of the fact that it might be hard to debug and test for contributors so it's probably an issue you have to solve on your own.

**Comment by Dode123** [comment]
This should also be extended for live games. Sometimes lobby can take a few hours to fill up for live, since our user-base is not massive low at the moment.

**Comment by gereon77** [comment]
@Longwelwind push... I agree to Tex that it should be extended for live also and users should get a mail when game has been started even if they turned off notifications or its a live game..

**Comment by gereon77** [comment]
Closed by #916 
For now it's only for PBEM games. I guess when you plan a live game you can write to the chat how to contact the host for starting the game. In case host stays online and keeps the tab opened he will be notified via sound and favicon change anyways. That was already done long ago.
