### ISSUE TITLE
Bug when resolving a march on splitting army. Unit moved but march order still present in originating region.

### ISSUE THREAD

**Issue by gereon77** [Longwelwind/swords-and-ravens#299]
https://swordsandravens.net/play/15441fca-b62b-41b2-abe6-0e71c4591455

Jason77 performed following march from Yronwood with original army FmKn:

Kn => Storms End.

When confirming nothing happened. Jason77 retried 5 times and then called me. I saw his knight in Storms End and asked him for reload. He then saw the knight there also. But:

The march is not present in game log and the march order has not been removed and can be performed again with the remaining footman in Yronwood:

![FF7F7D4C-1ECD-433F-8F2D-D9E62E6B17DD](https://user-images.githubusercontent.com/22304202/76147039-bd925200-6098-11ea-9b47-a929c3100a5f.jpeg)

**Comment by gereon77** [comment]
I tried to find the root cause of this bug but can't figure it out. As the knight was moved but not logged I assume that an exception is thrown in `moveUnits(...)`.

```
            // Execute the moves that don't trigger a fight
            movesThatDontTriggerAttack.forEach(([region, units]) => {
                this.resolveMarchOrderGameState.moveUnits(startingRegion, units, region);
            });

            if (movesThatDontTriggerAttack.length > 0) {
                this.actionGameState.ingameGameState.log({
                    type: "march-resolved",
                    house: this.house.id,
                    startingRegion: startingRegion.id,
                    moves: movesThatDontTriggerAttack.map(([r, us]) => [r.id, us.map(u => u.type.id)])
                });
            }
```

@Longwelwind : Do you see something in your logs?

**Comment by Longwelwind** [comment]
I got this error, I think it might be related: https://sentry.io/share/issue/84dd0b7a9288490f8b0ec40f6f73f444/

There's not a lot of meta information about the error (Adding proper logging to the game server would be a good thing), but the stacktrace should help.

**Comment by gereon77** [comment]
After reviewing this again and again I have no idea how it could have happened. @Longwelwind : May it be caused by #391 and have already been resolved?

**Comment by gereon77** [comment]
As it never happened again I close this now. Let's re-open it in case it really occurs again.
