### ISSUE TITLE
No notifications for PBEM games anymore

### ISSUE THREAD

**Issue by gereon77** [Longwelwind/swords-and-ravens#302]
I received no email for any of those games:

![1080F610-0CA9-4229-9C5F-FAD02EE9FF02](https://user-images.githubusercontent.com/22304202/76170103-19cfa180-617f-11ea-901f-427050fc159a.jpeg)

Spam folder has been checked.

**Comment by Longwelwind** [comment]
I still receive them, weirdly. I'll try to investigate the emails sent to your email in particular.

**Comment by gereon77** [comment]
Looks like problem is solved. But now I received a mail twice for a game which is in state "Bidding for CoK" https://swordsandravens.net/play/054a3d6c-4d19-4003-87cd-a9ce4b24dbde

I was wondering that all others have bid this fast but state is still "Waiting for others"... Maybe old non sent emails are coming now? Therefore it would be good to maybe show the current state of the game somehow?

**Comment by gereon77** [comment]
Ok I am flooded now with mails... Looks like the queue is coming now...

**Comment by gereon77** [comment]
I close this as it seems everything has been normalized now.
