### ISSUE TITLE
The game wrongly fast-tracked retreat location

### ISSUE THREAD

**Issue by Longwelwind** [Longwelwind/swords-and-ravens#323]
In [I am a god of tits and wine](https://swordsandravens.net/play/2a97224d-4037-4541-a309-1f8ecd1df1a4), when Martell lost the fight, the game directly retreated the attacking army to Port of Storm's End, instead of letting the Martell player choose between the 2 locations (Port of Storm's End and East Summersea).

I havn't looked into the cause, but it's probably because the game thought East Summersea was a bad location because moving the entire attacking army there would break supply's limit.

**Comment by gereon77** [comment]
I guess it’s a feature 😬 ESS is no valid retreat location and therefore Martell must retreat to port of SE.

![0D232804-ADAF-4754-9E4C-3C6A082946D2](https://user-images.githubusercontent.com/22304202/76691644-3a9b6980-664d-11ea-9b84-7dac0cae57a3.jpeg)

**Comment by Longwelwind** [comment]
Ah, yeah, indeed, I never played with this rule, so I have to get used to :P
