### ISSUE TITLE
Implement "Rumble in the South" and "Race to King's Landing" variants

### ISSUE THREAD

**Issue by gereon77** [Longwelwind/swords-and-ravens#330]
According to https://boardgamegeek.com/thread/803739/balanced-game-ideas-4-or-5-players right now SnR implemented "Struggle in the North". It would be nice to have the additional mentioned custom variants.

**Comment by Longwelwind** [comment]
A few things:

* As a first PR, only implement new setups, and no modified King's Court track.
* I think the setups can be encoded like this:
```
"setups": {
  "base-game": {
    "rumble-in-the-south": {
      "name": "Rumble in the South",
      "playerSetups": {
        "3": {
          ...
        },
        ...
      }
    }
  }
}
```
* Store the current selected setup in `entireGame.settings.setup` for example 🙂

**Comment by gereon77** [comment]
Note: It's also recommended to reduce the winning condition to 6 castles for "Rumble in the south".

**Comment by gereon77** [comment]
#367 introduce the new variants. Now we need to implement the Kings Court swap between Lannister and Stark for Rush to King‘s Landing
