### ISSUE TITLE
Starfall should be open in 5p mode

### ISSUE THREAD

**Issue by gereon77** [Longwelwind/swords-and-ravens#352]
To make the south a bit more attractive for Baratheon. Sorry that slipped through when reviewing the blocked regions.

**Comment by Longwelwind** [comment]
Is there a page somewhere where player discuss this kind of home-made rules?

For anything that deviate from the rules, I'd rather make sure that the community is behind the change before making anything

**Comment by gereon77** [comment]
In fact this mode has no official description. I suggest this change from my experience with this custom modification add I played it about 10 times already that way. We also tried Starfall closed but as already mentioned it was a bit weird as Baratheon then will always move north...

**Comment by gereon77** [comment]
After discussions on Discord it is right that you can consider Reach as Tyrell's 3rd easy castle. I still feel that without open Starfall Baratheon has no intention to take the southern sea but let's close this for now and see how it goes.
