### ISSUE TITLE
Siege Engines have combat strength of 0 when defending

### ISSUE THREAD

**Issue by gereon77** [Longwelwind/swords-and-ravens#353]
It should have happened in http://swordsandravens.net/play/886728da-d0bc-4531-bfdf-3af335b6b201 but as the game log does not show the units of the embattled area it is extreme hard to identify the supposedly wrong calculated battle.

**Comment by gereon77** [comment]
I can't reproduce the bug. The code looks fine, aside the little smell of the coexistence of two `getCombatStrengthOfArmy(...)` methods, where one is only used for calculating strength against neutral forces. I would rename and relocate that method as it took a while to follow what method is used for what.

My local tests where a Siege Engine defended a castle area and a non castle area are fine:

![image](https://user-images.githubusercontent.com/22304202/77055918-f653f480-69d1-11ea-9394-c61f311b507b.png)

![image](https://user-images.githubusercontent.com/22304202/77056423-ac1f4300-69d2-11ea-98c9-95692491ebc6.png)


@Longwelwind : If you agree I would close this issue after test and review of the code.

**Comment by Longwelwind** [comment]
Couldn't reproduce either. Though, by checking the code, I think it might be possible that siege engines will have a strength of 0 if they support an attack of an other player against a castle. I don't have time to check, I'll check later today.

**Comment by gereon77** [comment]
> 
> 
> Couldn't reproduce either. Though, by checking the code, I think it might be possible that siege engines will have a strength of 0 if they support an attack of an other player against a castle. I don't have time to check, I'll check later today.

I can do it and will report my investigation here.

**Comment by gereon77** [comment]
Indeed:

![image](https://user-images.githubusercontent.com/22304202/77060974-cad50800-69d9-11ea-82ae-9eb8fc2e6c35.png)

![image](https://user-images.githubusercontent.com/22304202/77061014-dd4f4180-69d9-11ea-8133-53188bec795c.png)
