### ISSUE TITLE
Show a preview of your musterings in the map

### ISSUE THREAD

**Issue by gereon77** [Longwelwind/swords-and-ravens#359]
That's the feedback from a user who hasn't played the board game that often yet. It was difficult for him to follow the musterings only from the list of musterings and the area names. A visualization would be nice.

**Comment by Dode123** [comment]
Also allow us to remove mustering choices in a single region, without having to reset all your mustering options. F. Ex I did mustering in 3 regions, and in the fourth I ended up with a unit combination (that I wanted), which required me to change my first region. Right now this forces you to reset everything and start over.

**Comment by gereon77** [comment]
> Qol change related to this:
> Also allow us to remove mustering choices in a single region, without having to reset all your mustering options. F. Ex I did mustering in 3 regions, and in the fourth I ended up with a unit combination (that I wanted), which required me to change my first region. Right now this forces you to reset everything and start over.

That is already possible by clicking the mustered Item in the list. ;)

**Comment by Dode123** [comment]
> > Qol change related to this:
> > Also allow us to remove mustering choices in a single region, without having to reset all your mustering options. F. Ex I did mustering in 3 regions, and in the fourth I ended up with a unit combination (that I wanted), which required me to change my first region. Right now this forces you to reset everything and start over.
> 
> That is already possible by clicking the mustered Item in the list. ;)

Wow mind blown. How did I not see this 😅😅

**Comment by aj-read** [comment]
Could we extend this to marches too? I think you should be able to see the units in the area where you’re marching them too before you click Confirm.

**Comment by Longwelwind** [comment]
I close this in favor of #653 which is a bit more detailed and encompass more modifications.
