### ISSUE TITLE
Users should be able to decline foreign support

### ISSUE THREAD

**Issue by gereon77** [Longwelwind/swords-and-ravens#362]
If you are supported by an other house you have no chance to decline that. For cards like Asha or Roose you might want to decline foreign support.

**Comment by Longwelwind** [comment]
During development, I wondered if I wanted to implement this, and I concluded that it would lengthen the time to resolve a battle.

There might be some way to make it not take an additional step, but I'd rather spend time otherwise for the moment. I'll put on Low Priority.

**Comment by vivard** [comment]
One option would be to add a toggle button during the attacking phase: refuse support if any support, no?

**Comment by Longwelwind** [comment]
This was discussed, and one of the issue is that if you get attacked, you might not even get the time to see this button (for example during a PBEM game).

The best solution, as described and implemented by Gereon, is to add a button during House card selection to refuse all support.
