### ISSUE TITLE
Automatically convert a stuck Live game into PBEM and abort stalled PBEM games after a TBD period of time

### ISSUE THREAD

**Issue by gereon77** [Longwelwind/swords-and-ravens#365]

**Comment by Dode123** [comment]
What time frame we looking at here? 
Live to PBEM time auto convert time: 1 hour? 
(some might take agreed upon short breaks for food etc) 

Pbem games auto abort. I think there should be a few options here to consider:

A) Inactive player in pbem. The other players do a vote kick. Then the replace player/vassal system comes in. Problem solved. 

B) Vote kick doesn't go through and/or there may be several afk players: After 3 days (?) the game will automatically send a poll to the players. Abort game or continue game. After a given time period, majority vote will ensure on said option. (ties favor continue game to reduce griefing). 
If aborted, no stats are recorded. 
PS: Should it be more strict for ranked games? 
If continued, any players that did not vote on the poll will be kicked by the system. Vassal and replacement system kicks in.

**Comment by gereon77** [comment]
> 
> 
> What time frame we looking at here?
> Live to PBEM time auto convert time: 1 hour?
> (some might take agreed upon short breaks for food etc)
> 

Well even if the time passed the host can set back to Live and disable notifications again. Technically there is no difference between Live and PBEM (E.g. maybe you already have seen others setting orders when you rejoined a game from a e-mail notification).
