### ISSUE TITLE
Speed filter when creating games 

### ISSUE THREAD

**Issue by Dode123** [Longwelwind/swords-and-ravens#383]
We should have a (optional) speed filter when creating new games. A new account will start with "average" speed on both live and pbem. If a host creates a new game, he can set a speed filter matching, or being lower, than his own speed for that mode (live/pbem) , for example "fast".

How many tiers we should have, and what their move speed metric should be is TBD. 
Example would be:
Very fast 
Fast 
Average 
Slow 
Very slow

**Comment by gereon77** [comment]
I put as not planned now as with #1314 I add the average PBEM response time to the profiles. Since there are very few live games anyway, I don't want to reduce them even further with a filter. Should the community grow, we can think about it again.
