### ISSUE TITLE
Battle no longer works if player is out of house cards

### ISSUE THREAD

**Issue by RipTheJacker** [Longwelwind/swords-and-ravens#394]
The game require both players to choose a house card in order to confirm a battle. If either player does not have a card to choose then the _Confirm_ button remains disabled and the game cannot continue.

**Comment by gereon77** [comment]
Relates to #392 and needs to be checked against Tyrion Lannister also.

**Comment by Longwelwind** [comment]
This should be fixed by #396.

For Tyrion Lannister, it's okay because his effect doesn't discard any additional card. If the opponent played its last card, then the rest of the combat will happen with no house card for them.

**Comment by RipTheJacker** [comment]
Was this deployed on the website? I think an additional change may be needed if so. I was mid-game when this happened: https://swordsandravens.net/play/2e4a18a9-fec9-47b6-b7c1-4acb3af84f6e

**Comment by Longwelwind** [comment]
Indeed, the change was not deployed.

I'll fix your game and deploy the change!

**Comment by RipTheJacker** [comment]
Sweet! I work in a React/Mobx stack but I don't know much about the game itself. I'll try to pick up some issues in the future though.
