### ISSUE TITLE
Add a player setting "Support myself automatically"

### ISSUE THREAD

**Issue by gereon77** [Longwelwind/swords-and-ravens#407]
I received the question why the game always asks for supporting yourself. I answered that this is how it's declared by the rulebook and it makes sense for house cards like Asha Greyjoy or Roose Bolton. But in fact 99% of battles you will support yourself. So I thought about a checkbox somewhere which will fast-track the decision if checked.

**Comment by gereon77** [comment]
Problem hereby is that in case you are defender but forgot to uncheck this setting, you supported yourself where you didn't want to. It's a really rare case though and in most battles you want to be supported by yourself but it should be handled properly. Just implementing it for attackers doesn't make much sense at all as attacker is the first to choose support and there you don't save time in PBEM games. So another solution would be to enable that setting by default for Houses who don't have such house card effects but it feels kinda inconsistent.

**Comment by gereon77** [comment]
Delgado has thrown in a new idea to solve this quite elegant and which would solve #362 also:

1. Automatically grant own support to all battles
2. When it comes to "Choose House card" add an additional button "Refuse all granted support"
3. When this option is selected the battle is reset to "Choose House card" with the new calculated strength without the support and both parties have to choose a new house card

@Longwelwind 
I like this idea but how should this 'reset' be translated into code, so in case it's PBEM the opponent will receive an e-mail that it's his turn again to chose a house card? Somehow we would need to end ChooseHouseCardGameState and reactivate it to trigger a state change. Or can it be also resolved by a new server message "support-refused"?

**Comment by Longwelwind** [comment]
I like this idea too, it's more clean and more UX-friendly since it's when you pick the House card that you think of whether you want to have no support.

**Comment by gereon77** [comment]
@Longwelwind Great! Of course it's ok to close the other PR.
I would love to implement this feature next after the high-priority issues so you can focus on the bugs I can't solve and vassals. If you could give me the right direction how solve the mentioned problem to re-trigger `ChooseHouseCardGameState` I would start asap.

**Comment by Longwelwind** [comment]
Multiple things:

* Automatically put both belligerents of a fight as supporting themselves at the beginning of the fight.
* Modify `ChooseHouseCardGameState` so that it accepts a `boolean` indicating whether player wants to refuse all support for this fight.
* When you add the checkbox in the UI of `ChooseHouseCardGameState`, try to put a tooltip or something to indicate what it does and why it's refusing support can be useful.
* I think that's all

**Comment by gereon77** [comment]
@Longwelwind Thx. But just to ensure we all talk about the same. Instead of a checkbox I expected a button which will reset the state for following scenario:

PBEM: A house attacks a region and has chosen his house card because attacker and defender automatically declared their support (no neutral supporters). Later the defender joins the game and refuses his support. The chosen house card of the attacker needs to be reset and he must be emailed again that it’s his turn again with the new battle strength. How do I achieve this?

**Comment by Longwelwind** [comment]
Ah, yeah, you're right, I forgot that one of the 2 houses may want to change his House card depending on whether the other House chose to forgo any support.

It's a bit more tricky in that case. I guess one of the solution to this would to reset the `childGameState` during a `ChooseHouseCardGameState`. This would re-send a notification to the other house and re-ask for the HouseCard.

It's not the most prettiest solution, but it would work.

**Comment by gereon77** [comment]
Ok thx. I go for this the next days as I had no luck with Roose...
