### ISSUE TITLE
Show possible orders for replacing with Raven when deciding between Order replacement or See top Wildlings card

### ISSUE THREAD

**Issue by gereon77** [Longwelwind/swords-and-ravens#440]
On the board game I know which orders I have left and what could be replaced before doing this decision. Here it is a bit harder to follow what I could change.

**Comment by Longwelwind** [comment]
Merging the two GameState might make it easier to solve this. Or maybe propose to change an order in the first place, and add a button "See the top WildlingCard instead"

**Comment by gereon77** [comment]
@Longwelwind up for grab?

**Comment by Longwelwind** [comment]
I thought of modifying the flow so that the first GameState that displayed is the one allowing an order to be modified, and add a button `See the Wildling Card instead` that would go to the next GameState (and maybe an `Ignore` button to skip the 2 phases altogether).

What do you think?

**Comment by gereon77** [comment]
Yes, that's the best solution I think.

**Comment by gereon77** [comment]
Grabbed
