### ISSUE TITLE
Total Land Area should have a counter (similar to amount of castles being listed)

### ISSUE THREAD

**Issue by Dode123** [Longwelwind/swords-and-ravens#443]
QOL. TLA is the primary tiebreaker now. It should be a clearly visible counter for TLA somewhere (left side of the unit info)? Many forget about its importance.

**Comment by gereon77** [comment]
You can count the land areas like you would need to do on board game. On the other hand the houses panels are ordered by the leading players. You always know who would win if game stops right now. That doesn’t mean we should not implement that but probably we should point out some of this „hidden“ features...

**Comment by Dode123** [comment]
> You can count the land areas like you would need to do on board game. On the other hand the houses panels are ordered by the leading players. You always know who would win if game stops right now. That doesn’t mean we should not implement that but probably we should point out some of this „hidden“ features...

I am aware that it can be counted.. lol. 
But its importance should be highlighted, many still forget about this being a tiebreaker. But of course it is of low importance.
