### ISSUE TITLE
Preemptive Raid's Night's Watch Victory effect doesn't correctly exclude someone from the next Wildling attack

### ISSUE THREAD

**Issue by Longwelwind** [Longwelwind/swords-and-ravens#446]

**Comment by Dode123** [comment]
Game in question:
https://swordsandravens.net/play/2cc4def9-793a-4a81-8221-f726dd4e6ae8 

By ignoring tyrell, martell was supposed to be lowest bidder, and needs to be placed at 0 supply. Then a ship needs to be killed in sea of dorne.

**Comment by Longwelwind** [comment]
Fixed the issue, and the bug should be fixed!
