### ISSUE TITLE
Stark was able to use attack of enemy

### ISSUE THREAD

**Issue by mmasztalerczuk** [Longwelwind/swords-and-ravens#455]
Log from game:

21:52 Stark attacked Greyjoy from The Twins to Winterfell with Knight, Knight.
21:52 Stark supported Stark.
21:53 Greyjoy supported Greyjoy.
21:55 House cards were chosen: Stark chose Roose Bolton Greyjoy chose Theon Greyjoy
21:55 Stark used the Valyrian Sword.
Stark won the fight!

Greyjoy suffered battle casualties because this units can't retreat: Siege Engine.
Greyjoy retreats from Winterfell to The Stony Shore.
21:57 Greyjoy marched from The Fingers:  Knight, Footman to The Twins

And in the same turn:

22:04 Stark attacked Greyjoy from Winterfell to The Stony Shore with Knight.

Greyjoy had march token on Winterfell and the order stay after Grejoy had to move after lose (so, stark could use him and made the second attack)

Turn 5
https://swordsandravens.net/play/df415ddd-99c3-4280-ab8a-fef76f7ea24e

**Comment by gereon77** [comment]
Looks like #299

**Comment by mmasztalerczuk** [comment]
Ok, I have found a bug (it is easy reproducable). When user is reconquered own capitol, game thinks that field belongs to the first owner (because defeated army of occupant fled, there is not any power token on conqured region, and capital has something like 'super-power-token'), so the order is not removed. I think that we should always remove order after battle from conquered field.

**Comment by Longwelwind** [comment]
You're right!

Since the capital directly goes back to the house, the game will think this is a simple march order and will not remove the order.

Thanks for the bug report, I'll check how to fix that
