### ISSUE TITLE
The rule to set an order to each region which is controlled by a unit can be bypassed

### ISSUE THREAD

**Issue by gereon77** [Longwelwind/swords-and-ravens#460]
After user hits the Ready button he can remove an order from the board which is a cheat. It would make sense to adapt #283 so the user only can change orders when game is in unready state.

@Longwelwind A long time ago you said on Discord that you imagined sth different and will describe it in the PR. I still wait for that. :)

**Comment by Longwelwind** [comment]
The idea was that anytime the player makes a modification, it unreadies him. There still could be a button to unready a player.

That would force the player to re-go through ready restrictions in order to confirm their orders, which would prevent the issue cited here.

**Comment by gereon77** [comment]
Yea that sounds good! I‘ll modify my PR and remove the unready button.

**Comment by Longwelwind** [comment]
The unready button can stay, in case someone is rethinking but doesn't have a clear plan on what to change yet.

**Comment by gereon77** [comment]
Good point! I keep it :)
