### ISSUE TITLE
Show a region tooltip with infos and resources

### ISSUE THREAD

**Issue by gereon77** [Longwelwind/swords-and-ravens#471]

**Comment by Longwelwind** [comment]
So, for this feature in particular, here's how I imagined it:

A tooltip when a region is hovered. Ideally with some delay to avoid it appearing too early when people hover the map. This tooltip would contain all the info about the region: controller, units, power tokens, garrison & neutral force, supply barrels, crown icons, ...

This would act as a "last resort" if the map is getting a bit too crowded.

**Comment by gereon77** [comment]
Additional note: When we show the controller of the region we can remove the order tooltip which shows its controller right now. We then could make the order transparent when hovering over it.
