### ISSUE TITLE
Renly Baratheon's ability does not maintain routed status

### ISSUE THREAD

**Issue by norielbit** [Longwelwind/swords-and-ravens#479]
At the moment, Renly Baratheon's ability creates a new knight from scratch when upgrading a footman. 

This causes the deletion of the unit's routed/wounded status, turning it back into a combat ready unit.
This interaction allows Baratheon to "reset" a wounded footman, that can be later be used in the same round for an attack, support or another defense if the region is attacked again.

Relevant ruling from the FAQ:
_Q: Can a player use Renly Baratheon to upgrade one of their routed footman?_
A: Yes. But the new unit remains routed until the end of the round.

**Comment by gereon77** [comment]
Indeed! Again a very good catch! That probably also affects Crow Killers and all other upgrade effects.
