### ISSUE TITLE
Send "Game ended" notification

### ISSUE THREAD

**Issue by gereon77** [Longwelwind/swords-and-ravens#481]
I ended a PBEM game right now: https://swordsandravens.net/play/c0cf9b5c-2d2b-4a69-9d50-7a501aa9af5e but received no further mail. So all other players have no idea that the game is over now.

**Comment by gereon77** [comment]
@Longwelwind up for grab?

**Comment by Longwelwind** [comment]
Yup!

I guess we can simply change `getWaitedUsers` so that it includes all the players. That way, they'll receive a notification when the game is finished

**Comment by gereon77** [comment]
Grabbed
