### ISSUE TITLE
Wildlings strength is not updated after Preemptive Raid

### ISSUE THREAD

**Issue by gereon77** [Longwelwind/swords-and-ravens#483]
This might be critical as users might think they bid for wildlings strength of 12:

![image](https://user-images.githubusercontent.com/22304202/78260152-ee31a400-74fd-11ea-922d-0ab0f3bec9e8.png)

**Comment by Longwelwind** [comment]
What's the final Wildling Strength after the Preemptive Raid's Wildling attack? Is it 0 because the firs attack was successfuly or the result of the second attack (0 if won, 4 if lost)?

**Comment by gereon77** [comment]
Good question. I‘d say 0 on won 4 on loss.

**Comment by gereon77** [comment]
Grabbed.
