### ISSUE TITLE
Ser Davos doesn't get a sword when Stannis is discarded

### ISSUE THREAD

**Issue by gereon77** [Longwelwind/swords-and-ravens#500]
In our game my footman in Dornish marches should have been killed:

https://swordsandravens.net/play/2a97224d-4037-4541-a309-1f8ecd1df1a4

**Comment by Longwelwind** [comment]
Based on preleminary analyses, it seems to me that Davos got his sword, but that the game did not, maybe due to the changes we did in `v1.3`.
