### ISSUE TITLE
Game log doesn’t state unit loss correctly when you can’t retreat to enemies capital

### ISSUE THREAD

**Issue by gereon77** [Longwelwind/swords-and-ravens#501]
By accident it really happened to me because I simply forgot that this will happen (maybe a warning would make sense):

Turn 3 in https://swordsandravens.net/play/6924757a-a666-4e57-97c3-c27788c31163

![E7347B7D-149F-4ECC-A5C3-ED9589AAA049](https://user-images.githubusercontent.com/22304202/78506734-057dc500-777c-11ea-9c88-31c79f12bb55.jpeg)

It should be cannot retreat to Dragonstone and the killed units (Kn, Fm) are missing.

**Comment by norielbit** [comment]
I'll take this
