### ISSUE TITLE
Find a way to do rebase from GitHub's UI

### ISSUE THREAD

**Issue by Longwelwind** [Longwelwind/swords-and-ravens#516]
This issue if more of a discussion.

Asking people to rebase their PRs is time-consuming. There are solutions listed there: https://github.com/isaacs/github/issues/88. I don't what's the best.

**Comment by gereon77** [comment]
I didn't go through all possible solutions but this seems to be easy and could be tested: https://github.com/isaacs/github/issues/88#issuecomment-456457979_

**Comment by Longwelwind** [comment]
Could not find a proper tool to do it.

GitHub Action doesn't allow to do that because PR from forks are not accessible with normal credentials, at least that's what I read from here: https://github.com/cirrus-actions/rebase/issues/12.

**Comment by gereon77** [comment]
Should be possible out of the box now.
