### ISSUE TITLE
Routed status is not updated properly

### ISSUE THREAD

**Issue by gereon77** [Longwelwind/swords-and-ravens#525]
![image](https://user-images.githubusercontent.com/22304202/78872059-f7b09400-7a48-11ea-993a-8dc621e3f5d2.png)

**Comment by gereon77** [comment]
Also the total combat strength should have been 10....

**Comment by gereon77** [comment]
As the list of PRs is quite long right now I wait until this issue gets the up for grab label. The fix is already available and quite easy.

**Comment by Longwelwind** [comment]
I tried to reproduce the bug, but I wasn't able to. Units are shown as routed.

Also I don't see how your branch fixes the issue.

**Comment by gereon77** [comment]
Yea, I thought move-units deletes the wounded unit and creates a fresh new one, so I thought sending wounded after move-units would help.

In fact when I did an other test on an other branch I also saw the unit as wounded without my fix. So maybe in the referenced game I lost the wounded message from the server?

**Comment by Longwelwind** [comment]
Maybe, it'd be weird, though.

This section of the code is not in any conditional path too, which makes it any weirder. I'll keep it open for a while if it re-happens. I'll close if it doesn't.

**Comment by Longwelwind** [comment]
Seems like nothing happened again. I'll close to clean up the backlog.
