### ISSUE TITLE
Display remaining Power Pool

### ISSUE THREAD

**Issue by norielbit** [Longwelwind/swords-and-ravens#532]
There is no indication for the remaining power pool, I think a hover tooltip on the power tokens with something like: available power tokens, power tokens on board and power tokens in pool could work for this.

**Comment by norielbit** [comment]
I worked something out:

![image](https://user-images.githubusercontent.com/18612633/79076467-0a55f200-7d03-11ea-9ad8-8eb3eb328daa.png)

Code changes:
https://github.com/Longwelwind/swords-and-ravens/compare/master...norielbit:power-use-tooltips

I thought moving `MAX_POWER_TOKENS` into a `Game` attribute is the best approach here, although it requires a migration as it fits with the way other game constants are kept.

**Comment by Longwelwind** [comment]
You can make a PR. For the tooltip, imo, you can have:

```
Baratheon
Available 6
On the board 1
Remaining 13
```

What do you think? I feel like there's too much repetition on the text, but maybe I'm cutting too much of it.

**Comment by norielbit** [comment]
I think that's better, although I don't like just "Remaining" for the Power Pool because it could be confusing with available. How about:
```
Baratheon
Available: 6
On the board: 1
Power Pool: 13
```

Is there a `v1.5` branch open yet, or should I open a PR to the master? I structured the change so that it requires a migration, so you might want to keep it for the next version
