### ISSUE TITLE
Game log should contain regions of lost units due to wildlings effects

### ISSUE THREAD

**Issue by gereon77** [Longwelwind/swords-and-ravens#549]
To allow a proper replay by the game log actions later.

**Comment by Longwelwind** [comment]
It would be good to have the regions inside the game logs.

Regarding replays, though, I'm not sure we will use game logs to enable them. I'm not entirely set on how to implement replay.

**Comment by gereon77** [comment]
Yea.. Probably the best solution would be to apply something like a command pattern with event sourcing.. But it would be a huge refactoring and maybe a bit oversized for a community project. As the game log contains already all necessary data to replay the game it would be a suitable solution, though it’s not ideal.

**Comment by gereon77** [comment]
Grabbed

**Comment by gereon77** [comment]
@Longwelwind When we add the region to the log interfaces now, they will be missing in old logs of course. How would you handle this? Somehow it feels like a hack to apply `string | null` to make it backwards compatible. On the other hand applying a default region like, let's say "dragonstone" seems to be weird. I also thought about a dummy region with name "Unknown" but it would have to be part of the `staticWorld` so it can be retrieved by the log component which again is weird.

**Comment by gereon77** [comment]
@Longwelwind When we add the region to the log interfaces now, they will be missing in old logs of course. How would you handle this? Somehow it feels like a hack to apply string | null to make it backwards compatible. On the other hand applying a default region like, let's say "dragonstone" seems to be weird. I also thought about a dummy region with name "Unknown" but it would have to be part of the staticWorld so it can be retrieved by the log component which again is weird.

**Comment by Longwelwind** [comment]
@gereon77 Don't hesitate to make a "Bump" comment if I ever missed a comment :P

I would go for `string | null`, with comments to explain why the variable could be `null`.

**Comment by gereon77** [comment]
I don't know what triggered me to open this issue but in fact all 3 wildlings effects which can kill units already contain a region->units map and the regions are already printed. Sorry!
