### ISSUE TITLE
Fast track raids when only other raid commands can be removed

### ISSUE THREAD

**Issue by norielbit** [Longwelwind/swords-and-ravens#551]
Raid order resolution can be fast tracked when **_all_** raid orders can only remove other raid orders. This should speed games somewhat but is otherwise not necessary.

**Comment by gereon77** [comment]
Hi @norielbit .. I hesitate to comment on the PR, that’s Long‘s job. But here are just my 5 cents. As there is already a fast tracking mechanism for raids I guess this issue can be solved easier which would follow the original way and doesn’t need a new log type.

See discussion in #438 for details

**Comment by Longwelwind** [comment]
>Hi @norielbit .. I hesitate to comment on the PR, that’s Long‘s job.

It's okay, feel free!

Indeed, we had an ongoing issue for this. I saw the PR, and I have to admit I'm not a super fan of the code. I like the current way of fast-tracking, and I'd rather improve on it than designing an entire different way of doing it.

**Comment by norielbit** [comment]
@Longwelwind No problem! I thought it would be nicer to have a clear message explaining why suddenly all the raids are gone, but I don't mind doing it similarly to the regular fast-tracking.
I'll close the PR for now and re-open once I got it to work on an order-by-order basis like the regular fast-tracking.
