### ISSUE TITLE
Show GMT and local time on games page for easier game session scheduling 

### ISSUE THREAD

**Issue by gereon77** [Longwelwind/swords-and-ravens#552]

**Comment by Longwelwind** [comment]
This idea seems nice, I just wouldn't now where to put, do you have an idea? :/

**Comment by gereon77** [comment]
Not that easy.. maybe in the right header of games table? And maybe just show one value there with the possibility to toggle it to local time. GMT could be the default...


![](https://user-images.githubusercontent.com/9724878/79630368-f1a96a00-8150-11ea-9386-bbd31d704543.png)

**Comment by gereon77** [comment]
Implemented by #679
