### ISSUE TITLE
Game log shows 2 successive marches of same user

### ISSUE THREAD

**Issue by gereon77** [Longwelwind/swords-and-ravens#560]
Game https://swordsandravens.net/play/5e8dc8b9-ebda-4c0e-9e77-460791b36ff4

![F341A2C3-2057-438F-944A-0153C133E6F7](https://user-images.githubusercontent.com/22304202/79715208-555ba080-82d3-11ea-8600-e9a178ad3f82.jpeg)

Jason 77 realized this issue. In fact the march order was correct. I wasn’t able to do both marches successively but the log definitely looks weird!

**Comment by Longwelwind** [comment]
I don't get the issue. Did Stark had 3 March orders and resolved them successively?

Imo, in this case, it's okay to have multiple consecutive logs.

**Comment by gereon77** [comment]
I was stark and it looks like I resolved my march from shivering sea to narrow and immediately after that the attack from moat to seagard. But in fact other houses marched in between...

**Comment by gereon77** [comment]
My fault... There were no other march orders left. A game log with all orders might help ;P
