### ISSUE TITLE
Allow spectators to join a game during the lobby stage

### ISSUE THREAD

**Issue by mrhappyasthma** [Longwelwind/swords-and-ravens#562]
In case you have a large group, it would be cool to have the ability to add spectators.

They would not be given any turns in the game or have any other action. Although they should probably be allow to chat (perhaps with their text in a different color to denote a spectator).

**Comment by mrhappyasthma** [comment]
Actually looks like you can join into ongoing games from the lobby.

Chatting works as a spectator, but there's not a great indication that the user is not actively playing in the game.

**Comment by mrhappyasthma** [comment]
I imagine a potentially better approach would be to disallow folks who open the game from chatting. But instead allow the lobby to designate specific people as "spectator" to allow for chatting.

**Comment by Longwelwind** [comment]
Spectators are allowed in the game, at the moment as you found out. As you said, there's not indication that they are not playing (except maybe the fact that there will be not star next to a house in the lower-left panel).

I never implemented it, but I wanted at first to add a new row to this panel, at the bottom, with the name of the spectators.

> I imagine a potentially better approach would be to disallow folks who open the game from chatting. But instead allow the lobby to designate specific people as "spectator" to allow for chatting.

Was there any issue in a game where this one was a problem? It would be good for some games, but most of games are "public" ones and I'd prefer to not change the way it works to satisfy one use-case while forgetting the others.

**Comment by mrhappyasthma** [comment]
Maybe that would only be an issue for "private" games. But that isn't implemented yet, so perhaps it's not a big concern?

you'd just be susceptible to malicious spammers, if that ever becomes a problem in the future

**Comment by Longwelwind** [comment]
Yup, indeed.

At the moment, it's okay, though. I'll close this issue for the time being, and we can re-open it and work on it later if the issue arrises, if that's okay with you. 🙂
