### ISSUE TITLE
[High priority] Catlyn Stark doubles the defense value of the house getting attacked

### ISSUE THREAD

**Issue by Dode123** [Longwelwind/swords-and-ravens#575]
![Annotation 2020-04-23 122133](https://user-images.githubusercontent.com/31342092/80088593-04f77380-855d-11ea-90eb-b1f367922b5a.jpg)

![Annotation 2020-04-23 122122](https://user-images.githubusercontent.com/31342092/80088597-05900a00-855d-11ea-8278-90aa249a76af.jpg)

Lannister get +4 defense value from their +2 defense order, so Catlyn house card effect triggers for Lannister. 

@Longwelwind Game link: https://swordsandravens.net/play/26c13cad-2f58-4e12-a71b-3e1679215bf4

**Comment by gereon77** [comment]
Grabbed
