### ISSUE TITLE
Improve the Westeros decks tooltips

### ISSUE THREAD

**Issue by norielbit** [Longwelwind/swords-and-ravens#596]
The current implementation (#594) is a bit obscure within the UI. 
As the Round counter / Wildling Threat row is mostly empty in the UI, it could be utilized for it like this:

![image](https://user-images.githubusercontent.com/18612633/80733539-82e7eb80-8b16-11ea-8e2c-27a1040a9bee.png)
The text is a bit hard to read, from left to right the things in the red rectangle are:
MoD IV deck, AFfC missions, Tides of Battle and Wildlings (hovering the threat icon should show the possible cards).
It's a bit crowded if all the icons are there but ignoring custom modes the IV and mission decks are mutually exclusive so that only 2 of the things in the rectangle may appear at once (ToB + IV or missions).

Ideally, I think the ability to look at the decks by image or a short description is important. Something like "no raids orders". Especially for the III deck its hard to remember all the cards, at least for me, but a more creative idea is probably needed for that.

**Comment by gereon77** [comment]
Do you see the Westeros tool tips on the live system? I don't see them on desktop neither. @Longwelwind I thought merging into master will trigger a deployment automatically?

**Comment by Longwelwind** [comment]
Yeah, but the pipeline failed.

I'll look into that.
