### ISSUE TITLE
Add a changelog

### ISSUE THREAD

**Issue by Longwelwind** [Longwelwind/swords-and-ravens#597]
Since we don't have releases anymore, we need to have a way to keep changes for end users.

The simplest idea would be to have a `CHANGELOG.md` file kept in the repository and modify it by adding a line describing the change everytime we do a PR, with the date the change was deployed. The only downside is that if a PR is done on one day, but merged in an other, the author of the PR must re-modify the changes to be up-to-date.

If any one has other ideas, I'm all ears!

**Comment by phi1-h** [comment]
Maybe generate the changelogs from git log? [Link](https://blogs.sap.com/2018/06/22/generating-release-notes-from-git-commit-messages-using-basic-shell-commands-gitgrep/)

**Comment by Longwelwind** [comment]
I'm not sure the git commits are enough to produce the changelog. I'd rather have something separated from the commits.

**Comment by Longwelwind** [comment]
This will be done in the forum to avoid having to ask people to update their PR with the correct date. This can be then be closed.
