### ISSUE TITLE
Renly bug when upgrading a footman that was not participating in the combat

### ISSUE THREAD

**Issue by Dode123** [Longwelwind/swords-and-ravens#605]
I moved with one footman from KL to reach. One footman left behind. This is confirmed by the combat window and log. 1 STR + renly for a total of 4 STR. I won the battle and it asked me if I wanted to upgrade a footman to knight. But.. It asked me WHICH of the two footman in KL, that I wanted to upgrade. This is not correct, as I only participated with one of them.

I must have picked the wrong one (that I didn't march with), because the game moved BOTH units into reach now, leaving KL empty. As you can see from the game log, I only marched with one of the two footman:

![Annotation 2020-05-02 103709](https://user-images.githubusercontent.com/31342092/80859394-f433b580-8c60-11ea-91ea-56b11ed822ec.jpg)
![Annotation 2020-05-02 103725](https://user-images.githubusercontent.com/31342092/80859393-f433b580-8c60-11ea-98d7-fa39a38d54ab.jpg)
![Annotation 2020-05-02 103734](https://user-images.githubusercontent.com/31342092/80859392-f39b1f00-8c60-11ea-8aeb-febae504a575.jpg)

Link https://swordsandravens.net/play/56212d78-ebb8-43b0-9740-004be9494c19

**Comment by gereon77** [comment]
In addition there is a blank missing in the log entry...

**Comment by gereon77** [comment]
@Longwelwind : I just can assume the root cause of the issue. I guess it's related to the fact that `AfterWinnerDeterminationGameState` is triggered before retreats are done and the attacking army is finally moved into the embattled area. So from my point of view that should be done in another order. I will PR my idea as draft. Let's discuss in the PR what side effects it can cause.

**Comment by gereon77** [comment]
Ok the bug is reproducable in the following way:

1. Use an army with 2 footman.
2. Attack with footman 1 and leave footman 2 in the startingRegion.
3. Win with Renly and select footman 2 for upgrade


I now check if my fix solve this issue (I think so and remove the draft then).
