### ISSUE TITLE
Switch to newly opened private chat after creating it

### ISSUE THREAD

**Issue by gereon77** [Longwelwind/swords-and-ravens#615]
To avoid writing to public chat

**Comment by gereon77** [comment]
Unfortunately it's hard to test as chat isn't working in my testing environment.

**Comment by Longwelwind** [comment]
The chat is handled by the website. To test this in a development environment, it requires to launch the website and the game server (in live mode). In the website UI, you then need to take the game id, the user secret, and insert it in the URL of the game server.

It's a tricky (and undocumented) setup to do, unfortunately.
