### ISSUE TITLE
Doran Martell causes players turn to be skipped

### ISSUE THREAD

**Issue by ShaneMcC** [Longwelwind/swords-and-ravens#616]
Possible bug with Doran Martell, which seems to be related to PR #499.

We had a game, that was up to Turn 7, 7998fb53-6883-433a-970f-e465e399f089

This turn started with a bid for the iron throne which resulted in:
> Final order for Iron Throne: Tyrell, Baratheon, Martell, Lannister, Greyjoy, Stark

Some non-relevent things happened, and then on Baratheon's turn (iron throne index 2):
> Baratheon attacked Martell from East Summer Sea to Sea of Dorne with Ship.

During this battle:
> House cards were chosen:
> 
> Baratheon chose Renly Baratheon
> Martell chose Doran Martell

And with that:
> Doran Martell: Martell decided to move Baratheon to the bottom of the Iron Throne track.

This results in a new Iron Throne order: Tyrell, Martell, Lannister, Greyjoy, Stark, Baratheon

Following that marching, the next player who got to march was Lannister (iron throne index 3)

This resulted in 2 things occuring:

1) Martell was skipped entirely that turn
2) Baratheon was able to take their second march order before anyone else (And before Martell was even able to take 1)

Perhaps this is intentional? But it felt unexpected to us.

**Comment by ShaneMcC** [comment]
Done some more reading on this, specificially:
 - https://boardgamegeek.com/thread/728660/doran-martell-house-card
 - https://community.fantasyflightgames.com/topic/291514-2-questions-about-doran-martell/

The latter of which points at: https://images-cdn.fantasyflightgames.com/filer_public/54/52/5452515d-61a6-47d3-898b-ee4913228b0b/va65_agot2_faq_v1_4.pdf

Which says at the bottom left of page 2:

> Q: Is it possible for a player’s turn be ‘skipped’ if the “Doran Martell” house card moves his token to the last position of the Iron Throne track?
> 
> A: Yes, it is possible for a House’s turn to be skipped after the resolution of Doran’s text ability.
> 
> The turn order of the Iron Throne track is always followed exactly as it appears; the “1” position goes first, followed by the “2” position, followed by position “3”, etc. It is the position on the track itself that determines the current player, regardless of which Houses have taken their turn.
> 
> For example, if the current player is in position “5” but is then moved to the end of the track (position “6”) as a result of Doran’ text ability, he would also be the next player, because position “6” always comes after position “5” no matter which Houses were occupying those slots previously. In the same way, the player whose House had previously been in position “6” (and is now in position “5”) must wait through another cycle of turns before resolving his next order.

So looks like this is as-intended, so I'll now close the issue. Sorry for the noise.

**Comment by Longwelwind** [comment]
Yup, it's a weird behaviour since the turn of someone is passed, but this is how it should work! 🙂
