### ISSUE TITLE
Game log improvements

### ISSUE THREAD

**Issue by vivard** [Longwelwind/swords-and-ravens#620]
It would be nice to arrange the log view, in order to have one tab for each round

**Comment by gereon77** [comment]
That's a quite nice idea! :) Something like the private chat select box would be nice you can select the full log or a specific round....

**Comment by gereon77** [comment]
In addition it would be nice if the log window could be a bit bigger. I don't know how to achieve that though. But the log is so important and just so small...

**Comment by gereon77** [comment]
I close this as #1691 already helps a lot
