### ISSUE TITLE
Improve map zooming/panning and fix the action panel so it's always visible when scrolling the map

### ISSUE THREAD

**Issue by gereon77** [Longwelwind/swords-and-ravens#622]

**Comment by Longwelwind** [comment]
[react-zoom-pan-pinch](https://www.npmjs.com/package/react-zoom-pan-pinch) seems to do the job. It would just need to be integrated inside the UI, and see if we should resize the map to accomodate for this.

**Comment by gereon77** [comment]
I close this for now as Action panel is now fixed on desktop. We can reopen that in case we want to improve it again.
