### ISSUE TITLE
Add indication which log entries are new since game log was last opened

### ISSUE THREAD

**Issue by gereon77** [Longwelwind/swords-and-ravens#623]
Something like this
![unknown](https://user-images.githubusercontent.com/22304202/80979706-fc8a1d00-8e27-11ea-8b9c-623ed81add1d.png)

**Comment by Longwelwind** [comment]
For this, we will need to store the last seen GameLog, for each user, somewhere.

I think it can be stored in `GameLogManager` with a `BetterMap<User, GameLog>`. The front-end can then send a `game-log-seen` whenever the game log tab is opened.

**Comment by gereon77** [comment]
Relates to #470
