### ISSUE TITLE
Transition to a hostless model for game administration

### ISSUE THREAD

**Issue by Longwelwind** [Longwelwind/swords-and-ravens#640]
At the beginning of the development, I envisioned a model for game handling where there was one owner of the game that would have full control on the settings of the game (modifying pre-game settings, cancelling the game, changing it into PBEM, ...).

I think the best model now would be:

* In the lobby phase, the game owner can do anything he wants: modifying the game settings, kick players, ...
* During the game, any modification to the game must be done by a vote accepted by  `rounded_down(2/3)` players. This includes cancelling the game, replacing a player by an other one, replacing a player by a vassal, ...

**Comment by Longwelwind** [comment]
Now that the vote system has been added, it will be easier to add functions for game management to players.

PBEM is still managed by the owner of the game. This should be changed in a future PR so that it requires a vote to be done.

**Comment by gereon77** [comment]
I like the current way of game administration. I close this for now.
