### ISSUE TITLE
Bug in winning conditions

### ISSUE THREAD

**Issue by vonbv25** [Longwelwind/swords-and-ravens#645]
Hi,

I would like to report a bug in the winning conditions. Here's the screenshot of the rule book:
![96688981_860338467813579_5384804089034964992_n](https://user-images.githubusercontent.com/5284384/81957425-1f45de00-963f-11ea-9e2d-c4a4fc81c9e9.png)

However, in our game, tyrell is clearly the winner by supply track, power token and position in the Iron Throne.
![97732528_567534267226674_408715594762813440_n](https://user-images.githubusercontent.com/5284384/81957539-4ac8c880-963f-11ea-9628-c1435fef2460.png)
![97261482_255004222387607_5743500121006407680_n](https://user-images.githubusercontent.com/5284384/81957551-4ef4e600-963f-11ea-89c8-cff1a6c69cf9.png)

**Comment by gereon77** [comment]
Errata v2 from 2019 updated winning conditions:

![3902B372-9CF7-4A24-9700-57CE4AE0C5D8](https://user-images.githubusercontent.com/22304202/81963001-d0834e80-9614-11ea-919d-4309b0ca2ecd.jpeg)

**Comment by Longwelwind** [comment]
I close, as the bug has been explained. 🙂
