### ISSUE TITLE
Make mustering more user-friendly

### ISSUE THREAD

**Issue by Longwelwind** [Longwelwind/swords-and-ravens#653]
At the moment, the process of mustering is not super user-friendly. You must move your mouse between the map and the top-right panel multiple times during the process, modifications are not shown in live on the map but in the top-right panel, ... All of these things make the process tedious and not user-friendly.

The goal of this issue is to discuss enhancements. At the moment, I see:

- [ ] Make the units appear on the map as they are mustered
- [ ] Put the list of possible musterings in a tooltip over the clicked region, instead of the top-right panel.

**Comment by gereon77** [comment]
An idea to solve the 2nd part of this issue can be found here: #677 By help of this contributors like me could be able to solve this issue.
