### ISSUE TITLE
Better visual animations/indications of moves

### ISSUE THREAD

**Issue by mrhappyasthma** [Longwelwind/swords-and-ravens#667]
Other than battles, there is very little that noticeably occurs on the board when users take actions. I find myself doing a ton of reading of the game log, even though I have the client open the entire time.

A good improvement might be to add more animations and visual indications along the same line of how the battle is done to draw attention. When playing without PBEM, this would make it a lot easier to follow.

Removing a token, could animate the token away. Marches that are just movements could be animated or highlighted in some color for a period of time or until the next player's move. Etc.

What do folks think of this idea? Also more suggestions of how to better illustrate moves are welcomed.

**Comment by mrhappyasthma** [comment]
Along the same lines, I think battles could be improved too. We could highlight the attacking territory as well, since that's not always clear. And perhaps highlight which territories were used to support. These could all be in different colors.

**Comment by gereon77** [comment]
Relates to #654
