### ISSUE TITLE
KnowsNextWildlingCard is not reset during Preemptive Raid or shows the next card during bidding for the current attack

### ISSUE THREAD

**Issue by gereon77** [Longwelwind/swords-and-ravens#675]
Yesterday another weird edge case bug happened to Jason77. You may remember that the top Wildlings card was "Preemptive Raid":

![IMG_2679](https://user-images.githubusercontent.com/22304202/82903993-1cfa5280-9f62-11ea-977b-86ef9383f59a.JPG)

However, when it came to the bidding for this attack it already showed the next card:

![67192616-e1b7-44ef-91be-56d3a9151192](https://user-images.githubusercontent.com/22304202/83220697-062b4a00-a174-11ea-9c4b-2122d068c228.JPG)

Jason77 thought, strange, but ok. When it says "Silence at the wall" there will be "Silence at the wall" now. Therefore he did the screenshot.

So I see two problems here. As another user reported that issue on Discord right now with other wildling cards the problem probably is that during a bidding the current wildling card already has been buried to the bottom of the deck and during a bidding for the current attack you probably see the next card. So we have to look deeper in that.

My first assumption was that `knowsNextWildlingCard` should be reset to false immediately after the card has been revealed and pushed to the bottom of the deck not after a wildlings attack has been completely handled. But on the other hand the goal should be to be able to see the tooltip during a bidding for the current wildlings attack also.

I haven't checked the code yet as yesterday when it appeared I had no access to and today I have to do other stuff and just wanted to explain it a bit more in detail.

**Comment by gereon77** [comment]
@Longwelwind up for grab as it’s an ugly bug?

**Comment by Longwelwind** [comment]
I've solved it in #681, you can check it if you want to see the details of implementation 🙂 

Thanks for the detailed bug report!

**Comment by gereon77** [comment]
@Longwelwind Thanks for your quick fix. :) It looks good and it should now work as expected so the seen card still is shown during the bidding for the current attack. 👍 

But have you considered Preemptive Raid and the second attack? I guess the user is now able to see the upcoming card for the second attack...
