### ISSUE TITLE
Performance issues with long-lasting game

### ISSUE THREAD

**Issue by AlecEJones** [Longwelwind/swords-and-ravens#682]
Hi there,

I've been engaged in a six-player game that is now in round 9 (#e8445464-37d3-4c0c-97c7-6397349a7374 for reference). All players involved in the game have noticed steadily decreasing performance on load as the game has progressed. We are all personally familiar with each other and use the chat window frequently.

The game has gone from normal load times in early to midgame, to starting to see loading problems by round 7. This affects us regardless of the browser being used (Firefox/Chrome/Brave). Upon game load, we must commonly wait at least a minute and see 2-3 browser-initiated 'slow script' warnings.

When the loading does complete, the chat window scrolls from the top to the bottom, through many hundreds of messages, until it reaches the bottom.  Lately, some players have been unable to enter the game at all, as the site will disconnect from the game before it is able to finish loading.

I have my suspicion that the requirement to load an excessive number of messages is contributing to these delays. Some basic optimization (such as limiting the number of chat messages that must be loaded) may be necessary.

**Comment by gereon77** [comment]
Thank you for your report! Instead of limiting the chat messages (like other GoT platforms do) I would prefer a paging solution which reloads older chat messages on request because cutting them off from the history might be problematic when we need to review chats because of reports for harassing...

**Comment by AlecEJones** [comment]
Bug report aside, is it possible to just have the chat messages of the game deleted? There's nothing critical or worth saving and it would probably let us wrap our game up.

**Comment by gereon77** [comment]
@Longwelwind surely can do that...

**Comment by Longwelwind** [comment]
Hi!

Indeed, at the moment, the game loads all the messages at load time, which creates the freeze.

A bigger overhaul of the chat client is planned in #318, to make it more user-friendly and to avoid the kind of problems described, but for the moment, I'll limit the fetched messages to 100, which should fix the issue with the load time of your game. When I find the time to work on the chat, I'll implement a proper load-on-scroll, similar to Discord/Slack/Mattermost/...

Thanks for the bug report!
