### ISSUE TITLE
Bug after wildling card "Crow Killers"

### ISSUE THREAD

**Issue by Hatschi7395** [Longwelwind/swords-and-ravens#685]
Hello, so long story short:
we lost the wildling attack and I had to replace two knights with footmen. I only had one footman left though, so I expected one Knight to die. Here is what happened: was able to replace both knights with footmen and the counter on the left showed me I had -1 footmen left. 
Here is a link to the game if that helps:
https://swordsandravens.net/play/34eabd91-ad5f-4e1d-bd2c-49011bb60f30

**Comment by gereon77** [comment]
@Longwelwind up4grab?

**Comment by Longwelwind** [comment]
Thanks!

> @Longwelwind up4grab?

Yup, it should be fairly easy to fix.

**Comment by gereon77** [comment]
> 
> 
> Thanks!
> 
> > @Longwelwind up4grab?
> 
> Yup, it should be fairly easy to fix.

Well.. I think it will be a bit more tricky than you might assume first because in case there are not enough footmen available we have to go to `SelectUnitsGameState` twice. First time to choose the knights to be killed and the second time to select the knight that finally will be degraded.
