### ISSUE TITLE
Not allowing me to march in line with my supply track

### ISSUE THREAD

**Issue by EPump** [Longwelwind/swords-and-ravens#694]
In this game (https://swordsandravens.net/play/8a0af9e7-9351-4901-a8fb-1db4ed757a20).

I am at 6 supply and currently am at my maximum army numbers:
4
3
2
2
2

I am attempting to march my army of 3 from the Eyrie in a split move that will break up my army of 3 and replace it with an army of 2 and two separate armies of 1:
-One unit marches into a new area to initiate battle (Crackclaw Point)
-One unit marches west to create a unit of 2 in the mountains of the moon with a unit that already occupies that territory
-One unit remains to occupy the Eyrie

![image](https://user-images.githubusercontent.com/66874333/84570119-bc845700-ad50-11ea-9129-9a887aaa385e.png)

This move should be legal, as it still adheres to my supply and replaces my army of 3 with an army of 2.  I understand that if I lose the battle it means my unit cannot retreat into the area it attacked from, but that is still preferable than not being able perform the move at all.

Perhaps this isn't a bug and there are rules I'm unfamiliar with regarding how units are counted when attacking prior to the outcome of the battle, but based on my understanding this should be allowed and isn't currently being supported as a viable option.

Thanks in advance for the support.

**Comment by gereon77** [comment]
You already answered your question:

> I understand that if I lose the battle it means my unit cannot retreat into the area it attacked from

That’s why this move is illegal, see FAQ:

![CA4956B0-4DDC-4918-A369-B97627E05915](https://user-images.githubusercontent.com/22304202/84571133-b2367d00-ad91-11ea-9c7e-2749308a72c6.jpeg)

**Comment by EPump** [comment]
Thank you!
