### ISSUE TITLE
Power not being given correctly

### ISSUE THREAD

**Issue by MikeyLear** [Longwelwind/swords-and-ravens#704]
In the bit where everyone's given power tokens, they were twice given out wrongly (we think). 4 player game, and both time all houses got one extra power, except Tyrell.

**Comment by Longwelwind** [comment]
Hi !

Can you link the game where the bug happened, and when (which turn, ...) it happened?

Thanks in advance!

**Comment by gereon77** [comment]
I assume all houses received one extra due to „trade with free cities“ except tyrell... @MikeyLear are you aware of that rule?
