### ISSUE TITLE
Garrisons are not correctly initialized for Base Game with DWD cards

### ISSUE THREAD

**Issue by gereon77** [Longwelwind/swords-and-ravens#792]
![image](https://user-images.githubusercontent.com/22304202/108090844-630cbe80-707b-11eb-8fc3-1a64223d44bb.png)

It's not reproducable on my local dev env but happens all the time when I create a base game with DWD cards.

**Comment by gereon77** [comment]
Fixed by #791

**Comment by rahim-got** [comment]
https://swordsandravens.net/play/a5c08686-4517-4b25-a2c2-65334c780223
