### ISSUE TITLE
Kevan Lannister Card Malfunction

### ISSUE THREAD

**Issue by KingKocan** [Longwelwind/swords-and-ravens#794]
The new Kevan Lannister (expansion card deck) did not provide any combat strength with no card cancelling his strength or anything like so. I have attached an image.
![C9DA7CBB-3C57-4E3F-B816-8C8FB1FA5154](https://user-images.githubusercontent.com/79272025/108386113-581c7000-71da-11eb-977d-ff87a658b2bd.png)

**Comment by gereon77** [comment]
@mmasztalerczuk can you have a look?

**Comment by mmasztalerczuk** [comment]
Yes. 
The config for ser kevan lannister looks fine. Maybe it is only problem with game log? I will try to reproduce that bug.

**Comment by mmasztalerczuk** [comment]
Ok, I have found a bug and I made a PR with fix -> https://github.com/Longwelwind/swords-and-ravens/pull/795

Asha Greyjoy had Balon ability ;) Sorry for that ;/

**Comment by gereon77** [comment]
Closed by #795

**Comment by KingKocan** [comment]
Appreciate the urgency, best game development team I know
