### ISSUE TITLE
Missing garrison for Kings Landing in DoD mode

### ISSUE THREAD

**Issue by rahim-got** [Longwelwind/swords-and-ravens#796]
The garrison of +5 for Kings Landing is missing when we use the DoD cards. I believe it is suppose to be gone if we played with the real DoD setup, but normal game just with DoD cards should resemble the original setup.
[https://share.getcloudapp.com/jkuem0Do](https://share.getcloudapp.com/jkuem0Do)

**Comment by gereon77** [comment]
Hi @rahim-got Thanks for your feedback. We thought we already fixed that issue: #792 Can you send us the link to that game?

**Comment by gereon77** [comment]
The garrison is here again: https://swordsandravens.net/play/b88710cc-e40f-4e3e-8686-533adb967251

**Comment by rahim-got** [comment]
Still some bugs with the garrisons.

No kraken for dinner lacks KL garrison and has a garrison at dragonstone
and old town.

**Comment by gereon77** [comment]
HI Rahim, can you provide the link to the bugged game?
