### ISSUE TITLE
Dance With Dragons - Rodrik the Reader causes game crash

### ISSUE THREAD

**Issue by srr013** [Longwelwind/swords-and-ravens#807]
Game crashed: https://swordsandravens.net/play/32f82fad-e5c4-4b23-ba2c-efbf8b37bd75

Playing Dance with Dragons beta

The Qyburn card was played in a combat. After combat the user selected the replacement card (Mace Tyrell). The user reported being able to accept the card selection, but afterwards was repeatedly asked to select a card. The game now hangs at the Authenticating screen for all players.

**Comment by gereon77** [comment]
Thanks for your report. I'll check the logs.

**Comment by gereon77** [comment]
When Rodrick can't be triggered game crashes.
