### ISSUE TITLE
Add PBEM mode

### ISSUE THREAD

**Issue by Longwelwind** [Longwelwind/swords-and-ravens#81]
Multiple things need to be done to implement this:

* Declare a common interface for `GameState` to list the players that need to act
* Detect when a new GameState was created after a player action, so that the list of players that have to act can be extracted and sent to the website
* Make an API in the Django's website that would allow the game server to send an email when it is the turn of a player.

**Comment by gereon77** [comment]
Havent received any mails yet.

**Comment by gereon77** [comment]
Tracked by #91
