### ISSUE TITLE
Dance with Dragons - Consolidate Power with * not allowing Muster action

### ISSUE THREAD

**Issue by srr013** [Longwelwind/swords-and-ravens#810]
Game: https://swordsandravens.net/play/32f82fad-e5c4-4b23-ba2c-efbf8b37bd75
Note: this is the same game that experienced an attack-phase issue with Rodrick. It's possible this could have caused the current issue.

Issue: Lannister and Greyjoy are able only to collect power tokens from their CP* orders; they are not able to muster units as there are no selectable options to muster units in the UI. Neither is facing supply limits. Current game state is on Greyjoy's CP Order.

**Comment by gereon77** [comment]
Somehow I should indicate more clearly that you have to click the region now to initiate a mustering.. I updated the GameState text but it is obviously not enough as Jason77 reported the same a few hours ago...
