### ISSUE TITLE
Valyrian steel blade can be used more than once per round

### ISSUE THREAD

**Issue by gereon77** [Longwelwind/swords-and-ravens#87]
Valyrian steel blade only can be used once. After usage it should be shown somehow that it is used. Maybe cross the blade symbol at the tracks?

**Comment by OrangePeanut1** [comment]
This happened again in the following test game:
https://swordsandravens.net/play/2a97224d-4037-4541-a309-1f8ecd1df1a4

Also even after second use I can still see the tooltip saying it's available (see screenshot)
![Screen Shot 2020-02-29 at 10 35 46 AM](https://user-images.githubusercontent.com/61632208/75613160-47fa1500-5adf-11ea-85d5-46a84044822e.png)
