### ISSUE TITLE
Changing orders should be acknowledged by a button

### ISSUE THREAD

**Issue by gereon77** [Longwelwind/swords-and-ravens#88]
Right now you only have to acknowledge your orders the first time. Any changes to your orders are sent directly to the server which might lead to a critical state.
It would be better if your changes will be submitted on a button which appears when you changed your already sent orders.

**Comment by Longwelwind** [comment]
To implement this, I think the best way is to:

* When the server receive a message from the player, it unreadies the player if he was ready. Client-side, this can also be checked and the payer can be unreadied.
