### ISSUE TITLE
UI issues

### ISSUE THREAD

**Issue by gereon77** [Longwelwind/swords-and-ravens#89]
- [x] Sometimes hovering over the revealed wilding card in game log doesn't increase it but make it blinking. Screenshot doesn't make sense here. All other cards are increased.

- [x] CoK bid slider is weird when user has no PTs left. For position 0 it shows the previous bidden value and can't be moved. Was not able to test if it bids 4 or 0 then on confirm. Maybe this bid can be skipped as it is clear that user will bid nothing when he has no PTs
![image](https://user-images.githubusercontent.com/22304202/72466189-b2c5ea00-37d8-11ea-9055-768c9e2c4032.png)

- [ ] Action Panel doesn't Update Westeros card after winter is coming
![image](https://user-images.githubusercontent.com/22304202/73056223-cd5e2a00-3e8e-11ea-8666-85f621cc29cd.png)

**Comment by gereon77** [comment]
Another missing blank []: "Martell attacked Tyrell from East Summer Sea[]to West Summer Sea with Ship, Ship."

**Comment by gereon77** [comment]
- when performing a march order the currently selected unit is hard to see. a significant highlighting would improve the usability

**Comment by gereon77** [comment]
Greyjoy raided Lannister's Consolidate Powerin Harrenhal from Riverrun

**Comment by gereon77** [comment]
Fixed issues:


- [x] add warning dialog when not all regions are ordered

- [x] spelling mistake: Place an Power Token


- [x] Missing blank: Baratheon, holder of the Raven token, chose to[]trigger a Game of Thrones.

- [x] During CoK the track which is currently bid for is not updated. (it shows "players bid for iron throne track even though they are bidding for fiefdoms or kings court. everything is fine after page reload

- [x] missing log entry for "march area in *** removed"

- [x] when resolving a march order without moving a unit display a confirmation alert dialog.

- [x] warn before submitting unused muster points. By accident we both didnt use all our muster points. I just mustered from 1 castle instead of 3 because it seemed I have to submit the current area. In fact it finished my turn.

- [x] Missing blank[]; Greyjoy raided Lannister's Consolidate Power[]in Harrenhal from Riverrun

- [x] When splitting armies a new line should be added to the display of the performed moves

- [x] A blank space [] would improve readability: "Final order for *** track:[]" and here: "Houses bid for the ***[]track:[]"

- [x] Another missing blank []: "Martell attacked Tyrell from East Summer Sea[]to West Summer Sea with Ship, Ship."

**Comment by gereon77** [comment]
New issues:

- [ ] add visual signal when its your turn. background turns white or sth like that
now tracked by #80

**Comment by gereon77** [comment]
@Longwelwind if ok i would delete the tracked by comment to not synchronize 2 locations

**Comment by gereon77** [comment]
@Longwelwind I also plan to fix the bid slider issue.

**Comment by Longwelwind** [comment]
>if ok i would delete the tracked by comment to not synchronize 2 locations

I didn't understand the proposition, sorry

>I also plan to fix the bid slider issue.

Ok!

**Comment by gereon77** [comment]
> > if ok i would delete the tracked by comment to not synchronize 2 locations
> 
> I didn't understand the proposition, sorry
> 
> > I also plan to fix the bid slider issue.
> 
> Ok!

@Longwelwind 
I want to delete my comment on this issue after the fixed issues comment. It’s the one containing the “Tracked by” issues.

**Comment by Longwelwind** [comment]
Yeah, remove the tasks here that are already present in an other issue.
