### ISSUE TITLE
Email notification doesn't work

### ISSUE THREAD

**Issue by gereon77** [Longwelwind/swords-and-ravens#91]
In the game "Test game with Jason77" I activated PBEM but didn't receive any email. I am registrated via Discord and I guess you use the email from there as the homepage doesn't offer sth to register an email under "Your profile" section.

Today I changed my discord email to my mobile email address with push notification to be notified immediately. So I thought this might be related to the issues and I checked the old Discord mail address and both spam folders. Nothing...

Jason77 also told me that he received nothing.

**Comment by Longwelwind** [comment]
Fixed.
