### ISSUE TITLE
Add base game 3 player mode

### ISSUE THREAD

**Issue by gereon77** [Longwelwind/swords-and-ravens#92]
I don’t really like 3p anymore but the benefit of this game mode is that it usually gets finished within less than 2h. And it’s fairly balanced in comparison to standard 4p and 5p.

Therefore it’s a good mode for newbies or for those who want to play live but don’t have that much time.

Of course later you should be able to switch between standard 3p or vassals.

**Comment by gereon77** [comment]
Related to #82

**Comment by gereon77** [comment]
Even if the decision will go for vassals it maybe would make sense to  offer at least the standard 2nd ed 3p mode. I personally don’t like this game mode but many other gamers do as it’s usually finished in less than 2h and therefore it’s a good mode for learning the game...

**Comment by gereon77** [comment]
Note: Remove the Lannister so from Port of Lannisport for this mode

**Comment by gereon77** [comment]
@Longwelwind As already mentioned on Discord... This game mode is not this hard to implement. Here is my very quick and dirty approach which works:

https://github.com/gereon77/swords-and-ravens/tree/add-base-3p-mode

And it looks this way:

![image](https://user-images.githubusercontent.com/22304202/75976369-9aba3f00-5eda-11ea-8057-27a757b8ca8f.png)

As you see there were just a few adaptions necessary to accomplish it but I know the solution is not ideal. Can we set up a Discord meeting where we can review how this transformation can be done better to keep a clean code design? Thx in advance :)

**Comment by gereon77** [comment]
Based on this we could also add custom 4p and 5p but instead of applying defeatable garrisons like described by rules we apply endless garrisons...

**Comment by Longwelwind** [comment]
Multiple questions:

* Why should the additional ship granted to Lannister be specifically removed for this game mode?
* Is Port of Pyke also blocked in this game mode?

**Comment by gereon77** [comment]
> Multiple questions:
> 
> * Why should the additional ship granted to Lannister be specifically removed for this game mode?

In 3p mode with the additional ship Lannister can move to GoldenSound and IronmansBay and therefore take Seagard and Riverrun in the first round which would overpower Lannister who is already quite strong in 3p.

> * Is Port of Pyke also blocked in this game mode?

Sure. If Pyke is blocked you can’t move into port anyways.
