### ISSUE TITLE
Implement automatic actions where possible for speeding up PBEM games and extend gamelog

### ISSUE THREAD

**Issue by gereon77** [Longwelwind/swords-and-ravens#95]
- [x] mace tyrell
- [x] retreat when there is just one possible area
- [x] Bid 0 when user has no tokens
- [x] Select casualties when there is only one unit type present in the area
- [x] Select units when possibleUnits.length equals toSelectCount
- [x] Choose last house card
- [x] Remove unusable raid orders

**Comment by gereon77** [comment]
In fact the bug was sitting in front of the computer. I had to select the unit to destroy which doesn't make sense from my point of view. Just kill it, and add a special entry in the log for it.

**Comment by Longwelwind** [comment]
It's true that technically we could fast track Mace Tyrell's ability.

One thing that I have noticed by people who played the game is that some things go too fast to understand what is going on (even with the game log). There are a lot of situations that could be fast-tracked by the game but that I purposedly left to the player to confirm (for example, choosing a retreat region even if there's only one available retreat region).

So, I'd let the players choose the unit in case of Mace Tyrell's ability.

**Comment by gereon77** [comment]
I see that point but be aware that most of the games will be PBEM games. And therefore automatically resolved actions will speed them up.

So I would go for automatic actions where possible and either make the automation transparent enough or disable automatic actions for live games?

**Comment by gereon77** [comment]
Same for choosing casualties when the army contains only one unit type:

![image](https://user-images.githubusercontent.com/22304202/72725233-836efe80-3b85-11ea-9e90-ff746dfa1b96.png)


The ship should be killed automatically and Stark only needs to decide the retreat area. In case there is only one area the retreat should be done automatically also.

**Comment by gereon77** [comment]
Same for "Use Valyrian stell blade question". That should only pop up if it makes sense to use it.

**Comment by gereon77** [comment]
@Longwelwind I suggest implementing at least "Fast track bidding when user has 0 tokens" and "Fast track removing of unusable raid orders" to speed up PBEM games. I already have a solution for the bidding in my fork and this is my idea of implementing fast tracking unusable raid orders:

Check if all raid orders of house are unusable and can't be raided themselves. An explicit check is needed as it might be possible that an unusable raid order in a land area has an adjacent sea area that contains a raid order. In that case the land raid order can't raid this sea order but can be raided by this. If there is no usable raid order which can't be raided resolving it can be fast tracked. From my point of view especially due to the rule to place an order in all areas with units it would make sense to fast track this if possible as users might use raid orders to fulfill this rule.

**Comment by gereon77** [comment]
Here is the implementation of the idea: https://github.com/gereon77/swords-and-ravens/tree/remove-unusable-raid-orders

**Comment by gereon77** [comment]
Fast tracking bids with 0 tokens still doesn’t work

**Comment by Dode123** [comment]
Also, please only ask to use steel blade if you are losing by one and thus using the blade would change the outcome of the battle.

**Comment by gereon77** [comment]
> Also, please only ask to use steel blade if you are losing by one and thus using the blade would change the outcome of the battle.

I removed that from the bullet point list yesterday as @Longwelwind pointed out, that some MoD cards have effects that rely on the final combat strength were you might want to add the additional sword strength even if you already won.
