### ISSUE TITLE
Daenerys Targaryen Appears to Not Respect Sword in PT Removal Calculation

### ISSUE THREAD

**Issue by srr013** [Longwelwind/swords-and-ravens#977]
Player played Daenerys and won. At prompt to use sword I used it to reduce the total difference from 2 to 1. Game still removed two tokens.

![image](https://user-images.githubusercontent.com/32019249/120348930-a5c17200-c2cb-11eb-9db3-28130b82da76.png)

https://swordsandravens.net/play/333f3ae8-548f-43eb-bfe0-61b91c7ea59d

**Comment by gereon77** [comment]
Thanks for your report. I‘ll look into that in time.

**Comment by gereon77** [comment]
I guess I already found the reason. Daenerys computes the Total combat strength after combat again but at this point your army is wounded already. So we either have to change it to an after winner determination gamestate or we have to use the newly introduced combatstats for calculation. If you send me the link to your game I give you the 1 PT back. Thx again!

**Comment by srr013** [comment]
Here's the game. Thanks for looking into this!
https://swordsandravens.net/play/333f3ae8-548f-43eb-bfe0-61b91c7ea59d
