### ISSUE TITLE
Raven holder can't use the replace order effect to set a complete new order for an empty region

### ISSUE THREAD

**Issue by gereon77** [Longwelwind/swords-and-ravens#99]

**Comment by Longwelwind** [comment]
It's actually an other bug in disguise, I think: players must put an order on each regions they have units in. If this was implemented, then the Raven holder would not be able to fill an empty region with an order.

It raises a question though: what should happen if a player doesn't have enough orders to fill all regions he occupies?

**Comment by gereon77** [comment]
True. Rulebook says each area must be filled with an order, unless you dont have enough orders when e.g. some order types are forbidden or you have just more than 15 territories...

from my point of view the only reason for this rule is to weaken the raven. lets assume you have exactly 15 territories. by this rule you just can use the raven to reveal the 1st card of the wildlings deck.

but for an online adaption i would recommend to slightly differ from the rulebook here. i would not force the users to order all regions to enable assigning an empty region for the raven. and due to the benefit that this is an online game you could still show dummy order tokens for the rest of the players for the empty regions so the opponents cant guess your strategy...

**Comment by Longwelwind** [comment]
Indeed, since it's an online adaptation, we could put dummy tokens.

I put this issue as low priority for the time being.

**Comment by gereon77** [comment]
6 weeks later I think we should follow the rulebook and just forbid sending "Ready" when there are empty regions but still valid orders.
